### ISSUE TITLE
mcmmo

### ISSUE THREAD

**Issue by dwa1275** [marcelo-mason/PreciousStones#1013]
[19:36:27] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[19:36:27] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
    at com.gmail.nossr50.util.player.UserManager.saveAll(UserManager.java:53) ~[?:?]
    at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:204) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193) [mcMMO.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

**Comment by marcelo-mason** [comment]
Doesn't seem to be related to PS.
