### ISSUE TITLE
Crash on 1.11 Spigot and paperspigot tested same error

### ISSUE THREAD

**Issue by arturek1666** [marcelo-mason/PreciousStones#1027]
Hi I am texting you because i have issue with your plugin. It gives an error when I run it on 1.11. And i am messaging you because i want to reopen my server however because of this crash i can't do anything and server is on whitelist. 

I understand you probably busy, can you please help me with this error I really love your plugin but really without this plugin my server will have no feature as this is one of most plugins I need for my server. Please message me back. Thank you, If you need more info about this error just message me back I will be happy to give more info if needed.

Using:
PaperSpigot Lastest, I also tested it with spigot for 1.11 and it's same results. 
The Error:
[22:31:54] [Server thread/ERROR]: Error occurred while enabling PreciousStones v10.4.1 (Is it up to date?)
org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:200) ~[patched_1.11.jar:git-Paper-924]
at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:60) ~[patched_1.11.jar:git-Paper-924]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:381) ~[patched_1.11.jar:git-Paper-924]
at net.sacredlabyrinth.Phaed.PreciousStones.managers.LanguageManager.loadFile(LanguageManager.java:61) ~[?:?]
at net.sacredlabyrinth.Phaed.PreciousStones.managers.LanguageManager.check(LanguageManager.java:44) ~[?:?]
at net.sacredlabyrinth.Phaed.PreciousStones.managers.LanguageManager.load(LanguageManager.java:35) ~[?:?]
at net.sacredlabyrinth.Phaed.PreciousStones.managers.LanguageManager.<init>(LanguageManager.java:30) ~[?:?]
at net.sacredlabyrinth.Phaed.PreciousStones.PreciousStones.onEnable(PreciousStones.java:127) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.jar:git-Paper-924]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.jar:git-Paper-924]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.jar:git-Paper-924]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [patched_1.11.jar:git-Paper-924]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [patched_1.11.jar:git-Paper-924]
at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:433) [patched_1.11.jar:git-Paper-924]
at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:394) [patched_1.11.jar:git-Paper-924]
at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:332) [patched_1.11.jar:git-Paper-924]
at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.jar:git-Paper-924]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:599) [patched_1.11.jar:git-Paper-924]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.nio.charset.MalformedInputException: Input length = 1
at java.nio.charset.CoderResult.throwException(CoderResult.java:281) ~[?:1.8.0_111]
at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339) ~[?:1.8.0_111]
at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:1.8.0_111]
at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.8.0_111]
at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:123) ~[patched_1.11.jar:git-Paper-924]
at java.io.Reader.read(Reader.java:140) ~[?:1.8.0_111]
at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:184) ~[patched_1.11.jar:git-Paper-924]
... 18 more
[22:31:54] [Server thread/INFO]: [PreciousStones] Disabling PreciousStones v10.4.1
[22:31:54] [Server thread/ERROR]: Error occurred while disabling PreciousStones v10.4.1 (Is it up to date?)
java.lang.NullPointerException
at net.sacredlabyrinth.Phaed.PreciousStones.helpers.ChatHelper.format(ChatHelper.java:790) ~[?:?]
at net.sacredlabyrinth.Phaed.PreciousStones.PreciousStones.log(PreciousStones.java:103) ~[?:?]
at net.sacredlabyrinth.Phaed.PreciousStones.PreciousStones.log(PreciousStones.java:113) ~[?:?]
at net.sacredlabyrinth.Phaed.PreciousStones.PreciousStones.onDisable(PreciousStones.java:207) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[patched_1.11.jar:git-Paper-924]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.11.jar:git-Paper-924]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.11.jar:git-Paper-924]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.jar:git-Paper-924]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [patched_1.11.jar:git-Paper-924]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [patched_1.11.jar:git-Paper-924]
at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:433) [patched_1.11.jar:git-Paper-924]
at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:394) [patched_1.11.jar:git-Paper-924]
at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:332) [patched_1.11.jar:git-Paper-924]
at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.jar:git-Paper-924]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:599) [patched_1.11.jar:git-Paper-924]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[22:31:54] [Server thread/INFO]: Done (5.272s)! For help, type "help" or "?"

**Comment by krustymk** [comment]
I have it running fine on 1.11 spigot
Did you grab the 1.11 version of PS and no the 1.10 by mistake?

**Comment by arturek1666** [comment]
Well i did get 1.11

**Comment by arturek1666** [comment]
Fixed issue after translating file i deleted it and working fine
