### ISSUE TITLE
Could not load 'plugins/PreciousStones-1.11.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by TheBadWorm** [marcelo-mason/PreciousStones#1050]
Hi!,
I have a problem with PreciosStones-1.11, it doesn't work. It worked before to reinstall my VPS's OS.
INFO:
```
java version "1.7.0_121"
OpenJDK Runtime Environment (rhel-2.6.8.1.el6_8-x86_64 u121-b00)
OpenJDK 64-Bit Server VM (build 24.121-b00, mixed mode)
```
`Plugins (15): Shopkeepers, WorldEdit, PlayerDeathLocation, SkinsRestorer, PermissionsBukkit, Vault, ClearLag, FoundDiamonds, WorldGuard, Essentials, EssentialsProtect, EssentialsSpawn, EssentialsChat, EssentialsAntiBuild, AuthMe`
```
[13:20:28 ERROR]: Could not load 'plugins/PreciousStones-1.11.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: net/sacredlabyrinth/Phaed/PreciousStones/PreciousStones : Unsupported major.minor version 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot.jar:git-Spigot-b4417b8-3c48711]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-b4417b8-3c48711]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-b4417b8-3c48711]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [spigot.jar:git-Spigot-b4417b8-3c48711]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.reload(CraftServer.java:748) [spigot.jar:git-Spigot-b4417b8-3c48711]
        at org.bukkit.Bukkit.reload(Bukkit.java:540) [spigot.jar:git-Spigot-b4417b8-3c48711]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-Spigot-b4417b8-3c48711]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-b4417b8-3c48711]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) [spigot.jar:git-Spigot-b4417b8-3c48711]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:636) [spigot.jar:git-Spigot-b4417b8-3c48711]
        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437) [spigot.jar:git-Spigot-b4417b8-3c48711]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-b4417b8-3c48711]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-b4417b8-3c48711]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-b4417b8-3c48711]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_121]
Caused by: java.lang.UnsupportedClassVersionError: net/sacredlabyrinth/Phaed/PreciousStones/PreciousStones : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_121]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803) ~[?:1.7.0_121]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_121]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442) ~[?:1.7.0_121]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:64) ~[?:1.7.0_121]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354) ~[?:1.7.0_121]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348) ~[?:1.7.0_121]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_121]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347) ~[?:1.7.0_121]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-b4417b8-3c48711]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-b4417b8-3c48711]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_121]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_121]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_121]
        at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_121]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-b4417b8-3c48711]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-b4417b8-3c48711]
        ... 14 more
```

**Comment by marcelo-mason** [comment]
You need Java 1.8

**Comment by TheBadWorm** [comment]
Ha, I solved before! Thank you for answer anyway, best useful plugin!
