### ISSUE TITLE
Really Important

### ISSUE THREAD

**Issue by arturek1666** [marcelo-mason/PreciousStones#1054]
From today your plugin doesn't work and i could not find way, I also try on spigot same rusts. Please help me as i needed to switch of my server of this time

```
[13:25:06] [Server thread/ERROR]: Error occurred while enabling PreciousStones v10.5.3 (Is it up to date?)
org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:200) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:146) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalarNonSpaces(ScannerImpl.java:1863) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalar(ScannerImpl.java:1846) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchFlowScalar(ScannerImpl.java:1029) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchSingle(ScannerImpl.java:1004) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:392) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:585) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:132) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:381) ~[patched_1.11.2.jar:git-Paper-1078]
	at net.sacredlabyrinth.Phaed.PreciousStones.managers.LanguageManager.loadFile(LanguageManager.java:61) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.managers.LanguageManager.check(LanguageManager.java:44) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.managers.LanguageManager.load(LanguageManager.java:35) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.managers.LanguageManager.<init>(LanguageManager.java:30) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.PreciousStones.onEnable(PreciousStones.java:128) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1078]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1078]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1078]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1078]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281) ~[?:1.8.0_111]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339) ~[?:1.8.0_111]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:1.8.0_111]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.8.0_111]
	at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:123) ~[patched_1.11.2.jar:git-Paper-1078]
	at java.io.Reader.read(Reader.java:140) ~[?:1.8.0_111]
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:184) ~[patched_1.11.2.jar:git-Paper-1078]
	... 36 more
[13:25:06] [Server thread/INFO]: [PreciousStones] Disabling PreciousStones v10.5.3
[13:25:06] [Server thread/ERROR]: Error occurred while disabling PreciousStones v10.5.3 (Is it up to date?)
java.lang.NullPointerException
	at net.sacredlabyrinth.Phaed.PreciousStones.helpers.ChatHelper.format(ChatHelper.java:790) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.PreciousStones.log(PreciousStones.java:104) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.PreciousStones.log(PreciousStones.java:114) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.PreciousStones.onDisable(PreciousStones.java:209) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[patched_1.11.2.jar:git-Paper-1078]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.11.2.jar:git-Paper-1078]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.11.2.jar:git-Paper-1078]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1078]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1078]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1078]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1078]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by marcelo-mason** [comment]
Seems like an issue with the language file.  Its a yml parsing error.  Paste the file contents [here](http://www.yamllint.com/) to see where the error is.

**Comment by marcelo-mason** [comment]
If there is no yaml error, then it's an error in one of the strings you replaced. It looks like you replaced one of the keys in the file (the left side of the ":" ), so when PS tried to look for that key it couldn't find it.  Check the server logs for the last thing that was done before the crash to give you an idea what string is broke in the file.  

Another probability is that you upgraded, and are using an outdated language file.

**Comment by arturek1666** [comment]
I did translate your plugin a bit

**Comment by marcelo-mason** [comment]
Deleting the language.yml file and letting PS regenerate it will fix your issue.  If you had changed things, you can compare this new file to your old one, and port back your changes.

**Comment by arturek1666** [comment]
OK,

**Comment by marcelo-mason** [comment]
Oh ok, yeah then you either deleted a whole line, or deleted the first part of one of the strings which you shouldn't change.  i.e. the bolded part here:

**_allowedList_**: "{yellow}Allowed: {aqua}{1.allowed}"

**Comment by arturek1666** [comment]
remove language file and new one work

**Comment by marcelo-mason** [comment]
Basically the error was (in this example) PS looking for the string named "allowedList" but couldn't find it, so it crapped out.

**Comment by marcelo-mason** [comment]
Yeah remove it and it will be fixed.

**Comment by arturek1666** [comment]
Going to use online software to compare 2 files and see what i change i should not

**Comment by arturek1666** [comment]
Ok i know why heh but it was fine when reload the plugin, but it happen after reset xD

**Comment by marcelo-mason** [comment]
Yep errors in the language file only show up when that specific language is used.  So probably had something to do with stuff that is printed out after reset.

**Comment by arturek1666** [comment]
It didn't like polish alphabet xD
