### ISSUE TITLE
Server Hang loading plugin

### ISSUE THREAD

**Issue by adamwbb** [marcelo-mason/PreciousStones#1086]
here is the log output on initial startup:

`28.07 23:11:55 [Server] INFO Enabling PreciousStones v10.5.3
28.07 23:11:55 [Server] INFO Version 10.5.3 loaded
28.07 23:11:55 [Server] INFO MySQL Connection successful
28.07 23:11:55 [Server] INFO Creating table: pstone_cuboids
28.07 23:11:55 [Server] INFO Creating table: pstone_fields
28.07 23:11:55 [Server] INFO Creating table: pstone_unbreakables
28.07 23:11:55 [Server] INFO Creating table: pstone_grief_undo
28.07 23:11:55 [Server] INFO Creating table: pstone_translocations
28.07 23:11:55 [Server] INFO Creating table: pstone_storedblocks
28.07 23:11:55 [Server] INFO Creating table: pstone_players
28.07 23:11:55 [Server] INFO Creating table: pstone_snitches
28.07 23:11:56 [Server] INFO Added new indexes to database
28.07 23:11:56 [Server] INFO Creating table: pstone_purchase_payments
28.07 23:11:56 [Server] ERROR Error at SQL Query: Duplicate key name 'key_grief_locs'
28.07 23:11:56 [Server] ERROR Error at SQL Query: Duplicate key name 'indx_field_owner'
28.07 23:11:56 [Server] ERROR Error at SQL Query: Duplicate key name 'unq_uuid'
28.07 23:11:56 [Server] ERROR Error at SQL Query: Duplicate key name 'inx_player_name'
28.07 23:11:56 [Server] ERROR Error at SQL Query: Duplicate key name 'indx_cuboids_owner'
28.07 23:11:56 [Server] ERROR Error at SQL Query: Duplicate key name 'indx_cuboids_parent'
28.07 23:11:56 [Server] ERROR Error at SQL Query: Duplicate key name 'indx_unbreakables_owner'
28.07 23:11:56 [Server] ERROR Error at SQL Query: Duplicate key name 'indx_storedblocks_1'
28.07 23:11:56 [Server] ERROR Error at SQL Query: Duplicate key name 'indx_storedblocks_2'
28.07 23:11:56 [Server] INFO Added new indexes to database`

and it hangs there until server process is killed

the same issue happens too when using sqlite 

when reloading the server you get this output

`28.07 23:14:42 [Server] INFO Preparing start region for level 2 (Seed: 7826167578441289788)
28.07 23:14:43 [Server] INFO Enabling PreciousStones v10.5.3
28.07 23:14:43 [Server] INFO Version 10.5.3 loaded
28.07 23:14:44 [Server] INFO MySQL Connection successful`

running version 10.5.3 on spigot 1.12

**Comment by adamwbb** [comment]
here is the output when it hangs when using sqlite:
`28.07 23:38:35 [Server] INFO Version 10.5.3 loaded
28.07 23:38:35 [Server] INFO SQLite Connection successful
28.07 23:38:35 [Server] INFO Creating table: pstone_cuboids
28.07 23:38:35 [Server] INFO Creating table: pstone_fields
28.07 23:38:35 [Server] INFO Creating table: pstone_unbreakables
28.07 23:38:35 [Server] INFO Creating table: pstone_grief_undo
28.07 23:38:35 [Server] INFO Creating table: pstone_translocations
28.07 23:38:35 [Server] INFO Creating table: pstone_storedblocks
28.07 23:38:36 [Server] INFO Creating table: pstone_players
28.07 23:38:36 [Server] INFO Creating table: pstone_snitches
28.07 23:38:37 [Server] INFO Added new indexes to database
28.07 23:38:37 [Server] INFO Creating table: pstone_purchase_payments
28.07 23:38:37 [Server] INFO Added new indexes to database`

sqlite on restart of sevrer:
`28.07 23:40:35 [Server] INFO Enabling PreciousStones v10.5.3
28.07 23:40:35 [Server] INFO Version 10.5.3 loaded
28.07 23:40:35 [Server] INFO SQLite Connection successful`

**Comment by adamwbb** [comment]
after having it sit for an hour i get this output:

```
9.07 00:15:23 [Server] WARN java.lang.NullPointerException
29.07 00:15:23 [Server] WARN at net.minecraft.server.v1_12_R1.PacketStatusListener.a(PacketStatusListener.java:124)
29.07 00:15:23 [Server] WARN at net.minecraft.server.v1_12_R1.PacketStatusInStart.a(SourceFile:23)
29.07 00:15:23 [Server] WARN at net.minecraft.server.v1_12_R1.PacketStatusInStart.a(SourceFile:8)
29.07 00:15:23 [Server] WARN at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:126)
29.07 00:15:23 [Server] WARN at net.minecraft.server.v1_12_R1.NetworkManager.channelRead0(NetworkManager.java:330)
29.07 00:15:23 [Server] WARN at net.minecraft.server.v1_12_R1.NetworkManager.channelRead0(NetworkManager.java:1)
29.07 00:15:23 [Server] WARN at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
29.07 00:15:23 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
29.07 00:15:23 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
29.07 00:15:23 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
29.07 00:15:23 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
29.07 00:15:23 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
29.07 00:15:23 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
29.07 00:15:23 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
29.07 00:15:23 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
29.07 00:15:23 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
29.07 00:15:23 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
29.07 00:15:23 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
29.07 00:15:23 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
29.07 00:15:23 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
29.07 00:15:23 [Server] WARN at net.minecraft.server.v1_12_R1.LegacyPingHandler.channelRead(SourceFile:94)
29.07 00:15:23 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
29.07 00:15:23 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
29.07 00:15:23 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
29.07 00:15:23 [Server] WARN at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
29.07 00:15:23 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
29.07 00:15:23 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
29.07 00:15:23 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
29.07 00:15:23 [Server] WARN at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
```

**Comment by adamwbb** [comment]
debug  mode on:

```
30.07 00:39:37 [Server] INFO Enabling PreciousStones v10.5.3
30.07 00:39:37 [Server] INFO Version 10.5.3 loaded
30.07 00:39:37 [Server] INFO SQLite Connection successful
30.07 00:39:37 [Server] INFO Creating table: pstone_cuboids
30.07 00:39:37 [Server] INFO CREATE TABLE IF NOT EXISTS `pstone_cuboids` (  `id` INTEGER PRIMARY KEY,  `parent` bigint(20) NOT NULL, `x` int(11) default NULL,  `y` int(11) default NULL, `z` int(11) default NULL,  `world` varchar(25) default NULL,  `minx` int(11) default NULL,  `maxx` int(11) default NULL,  `miny` int(11) default NULL,  `maxy` int(11) default NULL,  `minz` int(11) default NULL,  `maxz` int(11) default NULL,  `velocity` float default NULL,  `type_id` int(11) default NULL,  `data` tinyint default 0, `owner` varchar(16) NOT NULL,  `name` varchar(50) NOT NULL,  `packed_allowed` text NOT NULL, `last_used` bigint(20) Default NULL, `flags` TEXT NOT NULL, UNIQUE (`x`,`y`,`z`,`world`));
30.07 00:39:37 [Server] INFO Creating table: pstone_fields
30.07 00:39:37 [Server] INFO CREATE TABLE IF NOT EXISTS `pstone_fields` (  `id` INTEGER PRIMARY KEY, `x` int(11) default NULL,  `y` int(11) default NULL, `z` int(11) default NULL,  `world` varchar(25) default NULL,  `radius` int(11) default NULL,  `height` int(11) default NULL,  `velocity` float default NULL,  `type_id` int(11) default NULL,  `data` tinyint default 0, `owner` varchar(16) NOT NULL,  `name` varchar(50) NOT NULL,  `packed_allowed` text NOT NULL, `last_used` bigint(20) Default NULL, `flags` TEXT NOT NULL, UNIQUE (`x`,`y`,`z`,`world`));
30.07 00:39:38 [Server] INFO Creating table: pstone_unbreakables
30.07 00:39:38 [Server] INFO CREATE TABLE IF NOT EXISTS `pstone_unbreakables` (  `id` INTEGER PRIMARY KEY, `x` int(11) default NULL,  `y` int(11) default NULL,  `z` int(11) default NULL,  `world` varchar(25) default NULL,  `owner` varchar(16) NOT NULL,  `type_id` int(11) default NULL,`data` tinyint default 0, UNIQUE (`x`,`y`,`z`,`world`));
30.07 00:39:38 [Server] INFO Creating table: pstone_grief_undo
30.07 00:39:38 [Server] INFO CREATE TABLE IF NOT EXISTS `pstone_grief_undo` (  `id` INTEGER PRIMARY KEY,  `date_griefed` bigint(20), `field_x` int(11) default NULL,  `field_y` int(11) default NULL, `field_z` int(11) default NULL, `world` varchar(25) NOT NULL, `x` int(11) default NULL,  `y` int(11) default NULL, `z` int(11) default NULL, `type_id` int(11) NOT NULL,  `data` TINYINT NOT NULL,  `sign_text` varchar(75) NOT NULL);
30.07 00:39:38 [Server] INFO Creating table: pstone_translocations
30.07 00:39:38 [Server] INFO CREATE TABLE IF NOT EXISTS `pstone_translocations` (  `id` INTEGER PRIMARY KEY,  `name` varchar(36) NOT NULL, `player_name` varchar(16) NOT NULL,  `minx` int(11) default NULL,  `maxx` int(11) default NULL, `miny` int(11) default NULL,  `maxy` int(11) default NULL,  `minz` int(11) default NULL,  `maxz` int(11) default NULL, UNIQUE (`name`,`player_name`));
30.07 00:39:38 [Server] INFO Creating table: pstone_storedblocks
30.07 00:39:38 [Server] INFO CREATE TABLE IF NOT EXISTS `pstone_storedblocks` (  `id` INTEGER PRIMARY KEY,  `name` varchar(36) NOT NULL, `player_name` varchar(16) NOT NULL,  `x` int(11) default NULL,  `y` int(11) default NULL, `z` int(11) default NULL, `world` varchar(25) NOT NULL, `type_id` int(11) NOT NULL, `data` TINYINT NOT NULL, `sign_text` varchar(75) NOT NULL, `applied` bit default 0, `contents` TEXT NOT NULL, UNIQUE (`x`,`y`,`z`,`world`));
30.07 00:39:38 [Server] INFO Creating table: pstone_players
30.07 00:39:38 [Server] INFO CREATE TABLE IF NOT EXISTS `pstone_players` ( `id` bigint(20), `uuid` varchar(255) default NULL, `player_name` varchar(16) NOT NULL, `last_seen` bigint(20) default NULL, flags TEXT default NULL, PRIMARY KEY (`player_name`));
30.07 00:39:38 [Server] INFO Creating table: pstone_snitches
30.07 00:39:38 [Server] INFO CREATE TABLE IF NOT EXISTS `pstone_snitches` ( `id` bigint(20), `x` int(11) default NULL,  `y` int(11) default NULL, `z` int(11) default NULL,  `world` varchar(25) default NULL, `name` varchar(16) NOT NULL, `reason` varchar(20) default NULL, `details` varchar(50) default NULL, `count` int(11) default NULL, `date` varchar(25) default NULL, PRIMARY KEY  (`x`, `y`, `z`, `world`, `name`, `reason`, `details`));
30.07 00:39:38 [Server] INFO CREATE INDEX IF NOT EXISTS `indx_field_owner` ON `pstone_fields` (`owner`);
30.07 00:39:38 [Server] INFO CREATE UNIQUE INDEX IF NOT EXISTS `indx_players_uuid` ON `pstone_players` (`uuid`);
30.07 00:39:39 [Server] INFO CREATE UNIQUE INDEX IF NOT EXISTS `indx_player_name` ON `pstone_players` (`player_name`);
30.07 00:39:39 [Server] INFO CREATE INDEX IF NOT EXISTS `indx_cuboids_owner` ON `pstone_cuboids` (`owner`);
30.07 00:39:39 [Server] INFO CREATE INDEX IF NOT EXISTS `indx_cuboids_parent` ON `pstone_cuboids` (`parent`);
30.07 00:39:39 [Server] INFO CREATE INDEX IF NOT EXISTS `indx_unbreakables_owner` ON `pstone_unbreakables` (`owner`);
30.07 00:39:39 [Server] INFO Added new indexes to database
30.07 00:39:39 [Server] INFO Creating table: pstone_purchase_payments
30.07 00:39:39 [Server] INFO CREATE TABLE IF NOT EXISTS `pstone_purchase_payments` ( `id` bigint(20), `buyer` varchar(16) default NULL, `owner` varchar(16) NOT NULL, `item` varchar(20) default NULL,  `amount` int(11) default NULL, `fieldName` varchar(255) default NULL, `coords` varchar(255) default NULL);
30.07 00:39:39 [Server] INFO CREATE INDEX IF NOT EXISTS `indx_field_owner` ON `pstone_fields` (`owner`);
30.07 00:39:39 [Server] INFO CREATE UNIQUE INDEX IF NOT EXISTS `indx_players_uuid` ON `pstone_players` (`uuid`);
30.07 00:39:39 [Server] INFO CREATE UNIQUE INDEX IF NOT EXISTS `indx_player_name` ON `pstone_players` (`player_name`);
30.07 00:39:39 [Server] INFO CREATE INDEX IF NOT EXISTS `indx_cuboids_owner` ON `pstone_cuboids` (`owner`);
30.07 00:39:39 [Server] INFO CREATE INDEX IF NOT EXISTS `indx_cuboids_parent` ON `pstone_cuboids` (`parent`);
30.07 00:39:39 [Server] INFO CREATE INDEX IF NOT EXISTS `indx_unbreakables_owner` ON `pstone_unbreakables` (`owner`);
30.07 00:39:39 [Server] INFO Added new indexes to database
30.07 00:39:39 [Server] INFO finalizing queue
30.07 00:39:39 [Server] INFO clearing fields from memory
```

**Comment by adamwbb** [comment]
HEEELLLPPPP!!!!!

**Comment by adamwbb** [comment]
I have tried this on 6 different machines

all same results.

i have tried windows, debian, fedora, centos

**Comment by marcelo-mason** [comment]
have you changed **settings.version** on the config by any chance?  Should be 14.

**Comment by Coldene** [comment]
"when reloading the server you get this output"

There is a tiny chance you have alot of heavy duty plugins 
and are at the crazy knife edge scary abyss of not enough ram?
Daring to /reload in game with the above is just scary...

Try poke at copies of the glitchy .db 
with http://sqlitebrowser.org/ or something
till you fix what appears to be 
ERROR Error at SQL Query: Duplicate key name
