### ISSUE TITLE
PreciousStones + RandomTP-reborn

### ISSUE THREAD

**Issue by PolskiSzescian** [marcelo-mason/PreciousStones#1101]
I have latest PreciousStones and latest RandomTP-reborn
java.lang.NoClassDefFoundError: net/sacredlabyrinth/Phaed/PreciousStones/FieldFlag
at com.gmail.theposhogamer.CheckAmbient$1.run(CheckAmbient.java:79) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[mc.jar:git-Spigot-da42974-876d22c]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [mc.jar:git-Spigot-da42974-876d22c]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[14:35:22 WARN]: [RandomTP-Reborn] Task #1340 for RandomTP-Reborn v1.9 generated an exception
java.lang.NoClassDefFoundError: net/sacredlabyrinth/Phaed/PreciousStones/FieldFlag
at com.gmail.theposhogamer.CheckAmbient$1.run(CheckAmbient.java:79) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[mc.jar:git-Spigot-da42974-876d22c]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [mc.jar:git-Spigot-da42974-876d22c]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[14:35:22 WARN]: [RandomTP-Reborn] Task #1340 for RandomTP-Reborn v1.9 generated an exception
java.lang.NoClassDefFoundError: net/sacredlabyrinth/Phaed/PreciousStones/FieldFlag
at com.gmail.theposhogamer.CheckAmbient$1.run(CheckAmbient.java:79) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[mc.jar:git-Spigot-da42974-876d22c]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [mc.jar:git-Spigot-da42974-876d22c]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[14:35:22 WARN]: [RandomTP-Reborn] Task #1340 for RandomTP-Reborn v1.9 generated an exception
java.lang.NoClassDefFoundError: net/sacredlabyrinth/Phaed/PreciousStones/FieldFlag
at com.gmail.theposhogamer.CheckAmbient$1.run(CheckAmbient.java:79) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[mc.jar:git-Spigot-da42974-876d22c]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [mc.jar:git-Spigot-da42974-876d22c]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[14:35:22 WARN]: [RandomTP-Reborn] Task #1340 for RandomTP-Reborn v1.9 generated an exception
java.lang.NoClassDefFoundError: net/sacredlabyrinth/Phaed/PreciousStones/FieldFlag
at com.gmail.theposhogamer.CheckAmbient$1.run(CheckAmbient.java:79) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[mc.jar:git-Spigot-da42974-876d22c]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [mc.jar:git-Spigot-da42974-876d22c]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[14:35:22 WARN]: [RandomTP-Reborn] Task #1340 for RandomTP-Reborn v1.9 generated an exception
java.lang.NoClassDefFoundError: net/sacredlabyrinth/Phaed/PreciousStones/FieldFlag
at com.gmail.theposhogamer.CheckAmbient$1.run(CheckAmbient.java:79) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[mc.jar:git-Spigot-da42974-876d22c]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [mc.jar:git-Spigot-da42974-876d22c]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[14:35:22 WARN]: [RandomTP-Reborn] Task #1340 for RandomTP-Reborn v1.9 generated an exception
java.lang.NoClassDefFoundError: net/sacredlabyrinth/Phaed/PreciousStones/FieldFlag
at com.gmail.theposhogamer.CheckAmbient$1.run(CheckAmbient.java:79) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[mc.jar:git-Spigot-da42974-876d22c]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [mc.jar:git-Spigot-da42974-876d22c]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[14:35:22 WARN]: [RandomTP-Reborn] Task #1340 for RandomTP-Reborn v1.9 generated an exception
java.lang.NoClassDefFoundError: net/sacredlabyrinth/Phaed/PreciousStones/FieldFlag
at com.gmail.theposhogamer.CheckAmbient$1.run(CheckAmbient.java:79) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[mc.jar:git-Spigot-da42974-876d22c]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [mc.jar:git-Spigot-da42974-876d22c]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[14:35:22 WARN]: [RandomTP-Reborn] Task #1340 for RandomTP-Reborn v1.9 generated an exception
java.lang.NoClassDefFoundError: net/sacredlabyrinth/Phaed/PreciousStones/FieldFlag
at com.gmail.theposhogamer.CheckAmbient$1.run(CheckAmbient.java:79) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[mc.jar:git-Spigot-da42974-876d22c]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [mc.jar:git-Spigot-da42974-876d22c]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[14:35:22 WARN]: [RandomTP-Reborn] Task #1340 for RandomTP-Reborn v1.9 generated an exception
java.lang.NoClassDefFoundError: net/sacredlabyrinth/Phaed/PreciousStones/FieldFlag
at com.gmail.theposhogamer.CheckAmbient$1.run(CheckAmbient.java:79) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[mc.jar:git-Spigot-da42974-876d22c]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [mc.jar:git-Spigot-da42974-876d22c]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [mc.jar:git-Spigot-da42974-876d22c]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by piratjsk** [comment]
This is an issue with RandomTP plugin not PreciuosStones.
RandomTP is designed to work with old version of PS (before '[code reorganization](https://github.com/marcelo-mason/PreciousStones/commit/e210b15dd94a2b04d8faa42e2a947bd42a14e16d#diff-899a4d7fec3b0fbd0f11e585e86faced)' change committed in July 2015).
Basically all RandomTP author have to do to fix this issue is to change [import statement](https://github.com/AnOrdinaryDev/RandomTP/blob/master/%5BSpigot%5D%20RandomTP-Reborn/src/com/gmail/theposhogamer/CheckAmbient.java#L23) from `[...].PreciousStones.FieldFlag` to `[...].PreciousStones.field.FieldFlag`.
