### ISSUE TITLE
Delete this issue :(

### ISSUE THREAD

**Issue by andramil** [marcelo-mason/PreciousStones#1104]
Dont know how to delete issue. It wasnt PS bug. Sorry for spam.

**Comment by andramil** [comment]
When someone try to destroy head NOT named MHF_ there is:


```
[13:48:47 ERROR]: Could not pass event BlockBreakEvent to HeadDrops v2.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-93e20b3-b8f84f3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-93e20b3-b8f84f3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [server.jar:git-Spigot-93e20b3-b8f84f3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [server.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290) [server.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:83) [server.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.EntityPlayer.B_(EntityPlayer.java:254) [server.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1633) [server.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.World.h(World.java:1603) [server.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.WorldServer.l(WorldServer.java:688) [server.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1405) [server.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [server.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [server.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-93e20b3-b8f84f3]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-93e20b3-b8f84f3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at de.timolia.headdrops.SkullManager.isSkullCustom(SkullManager.java:38) ~[?:?]
        at de.timolia.headdrops.EventListener.onBlockBreak(EventListener.java:57) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor336.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-93e20b3-b8f84f3]
        ... 16 more

```

And after destroying MHF head there is nothink in console.
