### ISSUE TITLE
Why happens this, so i started a new very thin plugin server. This is what happened.

### ISSUE THREAD

**Issue by MrKiller01** [marcelo-mason/PreciousStones#1120]
I don't know why that since a few days I have problems with PS placing stones and getting error output on my console. I thought, well, only way to tackle this is start brand new. Made a folder, placed spigot 1.12.2 in it, a simple command file to start it, filled the eula, let it restart, and after that it took two plugins, permissionEx and PreciousStones. After the folders in the plugin were created, i looked at the console and saw this:

> [12:42:05] [Server thread/INFO]: Starting minecraft server version 1.12.2
[12:42:05] [Server thread/WARN]: To start the server with more ram, launch it as "java -Xmx1024M -Xms1024M -jar minecraft_server.jar"
[12:42:05] [Server thread/INFO]: Loading properties
[12:42:05] [Server thread/INFO]: Default game type: SURVIVAL
[12:42:05] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-b6ecf3b-fb423b8 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[12:42:06] [Server thread/INFO]: Debug logging is disabled
[12:42:06] [Server thread/INFO]: Using 4 threads for Netty based IO
[12:42:06] [Server thread/INFO]: Server Ping Player Sample Count: 12
[12:42:06] [Server thread/INFO]: Generating keypair
[12:42:07] [Server thread/INFO]: Starting Minecraft server on *:25565
[12:42:08] [Server thread/INFO]: Using default channel type
[12:42:09] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[12:42:09] [Server thread/INFO]: [PermissionsEx] Loading PermissionsEx v1.23.4
[12:42:09] [Server thread/INFO]: [PreciousStones] Loading PreciousStones v10.0.4
[12:42:09] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[12:42:10] [Server thread/INFO]: Preparing level "world"
[12:42:10] [Server thread/INFO]: -------- World Settings For [world] --------
[12:42:10] [Server thread/INFO]: Item Merge Radius: 2.5
[12:42:10] [Server thread/INFO]: Item Despawn Rate: 6000
[12:42:10] [Server thread/INFO]: Experience Merge Radius: 3.0
[12:42:10] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[12:42:10] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[12:42:10] [Server thread/INFO]: View Distance: 10
[12:42:10] [Server thread/INFO]: Arrow Despawn Rate: 1200
[12:42:10] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[12:42:10] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[12:42:10] [Server thread/INFO]: Cactus Growth Modifier: 100%
[12:42:10] [Server thread/INFO]: Cane Growth Modifier: 100%
[12:42:10] [Server thread/INFO]: Melon Growth Modifier: 100%
[12:42:10] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[12:42:10] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[12:42:10] [Server thread/INFO]: Sapling Growth Modifier: 100%
[12:42:10] [Server thread/INFO]: Wheat Growth Modifier: 100%
[12:42:10] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[12:42:10] [Server thread/INFO]: Vine Growth Modifier: 100%
[12:42:10] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[12:42:10] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[12:42:10] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[12:42:10] [Server thread/INFO]: Mob Spawn Range: 4
[12:42:10] [Server thread/INFO]: Random Lighting Updates: false
[12:42:10] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[12:42:10] [Server thread/INFO]: Max TNT Explosions: 100
[12:42:10] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[12:42:10] [Server thread/INFO]: Structure Info Saving: true
[12:42:13] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[12:42:13] [Server thread/INFO]: Item Merge Radius: 2.5
[12:42:13] [Server thread/INFO]: Item Despawn Rate: 6000
[12:42:13] [Server thread/INFO]: Experience Merge Radius: 3.0
[12:42:13] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[12:42:13] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[12:42:13] [Server thread/INFO]: View Distance: 10
[12:42:13] [Server thread/INFO]: Arrow Despawn Rate: 1200
[12:42:13] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[12:42:13] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[12:42:13] [Server thread/INFO]: Cactus Growth Modifier: 100%
[12:42:13] [Server thread/INFO]: Cane Growth Modifier: 100%
[12:42:13] [Server thread/INFO]: Melon Growth Modifier: 100%
[12:42:13] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[12:42:13] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[12:42:13] [Server thread/INFO]: Sapling Growth Modifier: 100%
[12:42:13] [Server thread/INFO]: Wheat Growth Modifier: 100%
[12:42:13] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[12:42:13] [Server thread/INFO]: Vine Growth Modifier: 100%
[12:42:13] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[12:42:13] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[12:42:13] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[12:42:13] [Server thread/INFO]: Mob Spawn Range: 4
[12:42:13] [Server thread/INFO]: Random Lighting Updates: false
[12:42:13] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[12:42:13] [Server thread/INFO]: Max TNT Explosions: 100
[12:42:13] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[12:42:13] [Server thread/INFO]: Structure Info Saving: true
[12:42:14] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[12:42:14] [Server thread/INFO]: Item Merge Radius: 2.5
[12:42:14] [Server thread/INFO]: Item Despawn Rate: 6000
[12:42:14] [Server thread/INFO]: Experience Merge Radius: 3.0
[12:42:14] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[12:42:14] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[12:42:14] [Server thread/INFO]: View Distance: 10
[12:42:14] [Server thread/INFO]: Arrow Despawn Rate: 1200
[12:42:14] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[12:42:14] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[12:42:14] [Server thread/INFO]: Cactus Growth Modifier: 100%
[12:42:14] [Server thread/INFO]: Cane Growth Modifier: 100%
[12:42:14] [Server thread/INFO]: Melon Growth Modifier: 100%
[12:42:14] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[12:42:14] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[12:42:14] [Server thread/INFO]: Sapling Growth Modifier: 100%
[12:42:14] [Server thread/INFO]: Wheat Growth Modifier: 100%
[12:42:14] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[12:42:14] [Server thread/INFO]: Vine Growth Modifier: 100%
[12:42:14] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[12:42:14] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[12:42:14] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[12:42:14] [Server thread/INFO]: Mob Spawn Range: 4
[12:42:14] [Server thread/INFO]: Random Lighting Updates: false
[12:42:14] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[12:42:14] [Server thread/INFO]: Max TNT Explosions: 100
[12:42:14] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[12:42:14] [Server thread/INFO]: Structure Info Saving: true
[12:42:15] [Server thread/INFO]: Preparing start region for level 0 (Seed: -440367457973207033)
[12:42:17] [Server thread/INFO]: Preparing spawn area: 0%
[12:42:19] [Server thread/INFO]: Preparing spawn area: 1%
[12:42:20] [Server thread/INFO]: Preparing spawn area: 10%
[12:42:21] [Server thread/INFO]: Preparing spawn area: 44%
[12:42:21] [Server thread/INFO]: Preparing start region for level 1 (Seed: -440367457973207033)
[12:42:22] [Server thread/INFO]: Preparing spawn area: 41%
[12:42:23] [Server thread/INFO]: Preparing start region for level 2 (Seed: -440367457973207033)
[12:42:24] [Server thread/INFO]: [PermissionsEx] Enabling PermissionsEx v1.23.4
[12:42:24] [Server thread/INFO]: [PermissionsEx] Initializing file backend
[12:42:24] [Server thread/INFO]: [PreciousStones] Enabling PreciousStones v10.0.4
[12:42:24] [Server thread/INFO]: [PreciousStones] Version 10.0.4 loaded
[12:42:25] [Server thread/INFO]: [PreciousStones] SQLite Connection successful
[12:42:25] [Server thread/INFO]: [PreciousStones] Creating table: pstone_cuboids
[12:42:25] [Server thread/INFO]: [PreciousStones] Creating table: pstone_fields
[12:42:25] [Server thread/INFO]: [PreciousStones] Creating table: pstone_unbreakables
[12:42:25] [Server thread/INFO]: [PreciousStones] Creating table: pstone_grief_undo
[12:42:25] [Server thread/INFO]: [PreciousStones] Creating table: pstone_translocations
[12:42:25] [Server thread/INFO]: [PreciousStones] Creating table: pstone_storedblocks
[12:42:25] [Server thread/INFO]: [PreciousStones] Creating table: pstone_players
[12:42:25] [Server thread/INFO]: [PreciousStones] Creating table: pstone_snitches
[12:42:25] [Server thread/INFO]: [PreciousStones] Added new indexes to database
[12:42:25] [Server thread/INFO]: [PreciousStones] Creating table: pstone_purchase_payments
[12:42:25] [Server thread/INFO]: [PreciousStones] Added new indexes to database
[12:42:26] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[12:42:26] [Server thread/INFO]: Done (16,243s)! For help, type "help" or "?"
[12:42:26] [Craft Scheduler Thread - 3/WARN]: [PreciousStones] Plugin PreciousStones v10.0.4 generated an exception while executing task 6
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at ps.org.mcstats.Metrics.postPlugin(Metrics.java:363) ~[?:?]
	at ps.org.mcstats.Metrics.access$500(Metrics.java:68) ~[?:?]
	at ps.org.mcstats.Metrics$1.run(Metrics.java:255) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_162]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]

> 
Now, I do not understand a thing about this, you might, but I would love to know what went wrong...
Thanks....Mr Marcelo-Mason

**Comment by frizzbee30** [comment]
you're using the wrong version of PS by the look of it  :)


1.12 | 10.7.2 | 1.12.1-R0.1-SNAPSHOT



WARN]: [PreciousStones] Plugin PreciousStones v10.0.4 
-- | -- | --

**Comment by MrKiller01** [comment]
By the look of it..... I downloaded it fresh from the site....
Yes, I have seen this discrepancy and I don't know how to handle it, either versions did not have the block I need to configure.... Like godstone etc... there are only a few. I can remember a few years back that there were a whole lot of blocks available to change and use, now for some reason it is diminished... That's why I thought that the small size of the latest version was wrong, an error, but the version you refer, and in which the error I showed, is twice as big.... Confusion....
I wanted on my server which had the latest running place teleporters from one block to receiver block, that worked half... See, too difficult to simply explain.
I 'll try again after I retraced all steps to make sure I have not skipped somewhere a vital step.

**Comment by frizzbee30** [comment]
ignore the site and go to Jenkins, I've personally not used the site for a couple of years, same for many other plugins.  :)

With regard to the blocks, you generally need to add them yourself, or amend them, the plugin is amazingly customisable, but certainly doesn't 'spoon feed' server admins.

 Personally I think it can't be beat, fantastically flexible and I think most probably only use a small percentage of it's capabilities in often different ways  :D

**Comment by MrKiller01** [comment]
Ok, I got it clearer now, I shall try to explain. We manage two servers on bungeecord, first server I had edited the config game and took a lot of unused blocks out. The second server is one not edited by me but someone I cannot reach anymore. The blocks he used were extended with additions in the form of transporterblocks (white stained glass sends people to black stained glass block.) I can not reproduce this and lately I have problems using the blocks myself. Deleted myself from permissions, nada. Another person with same group rights in PermissionsEx, she steps on them glass blocks and it works for her...
I am really puzzled how it works to add a block and appoint an action to this block, and where I might find a solution of my avatar not interacting with those glass stained blocks, even the ones I made myself...
Maybe this is a bit more clear, and that error might be the old version stumbling over the unknown block I tried to add.... unknowingly that it was the older version.

**Comment by MrKiller01** [comment]
Thanks Frisbee, but i got this feeling that you don't know either...(how to add a stone and let m do what I want, transport to another stone(as i described before))
I replaced some stones to less important ones, and in my world: Godstone i made emerald block, but with all testing I thought, lets throw my config aside and let it rebuild new, see what happens... The thing i thought that happened, happened. My placed emerald block did nothing, as expected. After I altered the config on only that stone, I rebooted the server. The godstone I placed long time ago, worked again, as expected.
As of the Cityprotection, diamondblock, i placed one to test it again, I had not used this one before and I wanted a large area to protect at once. It gave me this error...

> [11:58:52 ERROR]: Could not pass event BlockPlaceEvent to PreciousStones v10.7.2

org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:500) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:485) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlac
eEvent(CraftEventFactory.java:150) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8
]
        at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:207)
 [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractM
anager.java:505) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.jav
a:951) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseIt
em.java:37) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseIt
em.java:1) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:
13) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.
12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:
748) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:
406) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:
679) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.jav
a:577) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NoClassDefFoundError: br/net/fabiozumbi12/RedProtect/API/Re
dProtectAPI
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.RedProtectManager.c
anBuild(RedProtectManager.java:65) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.RedProtectManager.c
anBuildField(RedProtectManager.java:90) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.PermissionsManager.
canBuildField(PermissionsManager.java:160) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.ForceFieldManager.a
dd(ForceFieldManager.java:102) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.listeners.PSBlockListener.on
BlockPlace(PSBlockListener.java:740) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_161]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_161]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:302) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        ... 18 more
Caused by: java.lang.ClassNotFoundException: br.net.fabiozumbi12.RedProtect.API.
RedProtectAPI
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_161]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:152) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:100) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.RedProtectManager.c
anBuild(RedProtectManager.java:65) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.RedProtectManager.c
anBuildField(RedProtectManager.java:90) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.PermissionsManager.
canBuildField(PermissionsManager.java:160) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.ForceFieldManager.a
dd(ForceFieldManager.java:102) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.listeners.PSBlockListener.on
BlockPlace(PSBlockListener.java:740) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_161]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_161]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:302) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        ... 18 more
>
So, now I am puzzled, again, config is brand new, no altercations except the godstone item... but yet when I hold a diamond block in my hand, it says City Protection.... yet it does nothing except generate the error above on the console.....
Now, that is not logical....

>

**Comment by MrKiller01** [comment]
As I looked over the error I found that one plugin was biting, red protect, so I removed that one and also residence, to make sure this would not interfere too.
Still, now, as I restarted the server, the cityprotection worked again.... Weird that these two would interfere one another. 
Still I would like to know what to do to make those transporter blocks function......
Anyone?

**Comment by frizzbee30** [comment]
Hi, no idea on the transport function as we use it purely for anti-grief, and not to it's full capacity. We too have found that some plugins do interact and break the plugin, but in the past the dev has been great at fixing this  :)

**Comment by MrKiller01** [comment]
I actually was hoping that mr Mason would tell us how to add blocks and give them a function, as I showed, the settings from the second server to the first, (on the second server the transporter blocks work) the blocks are only recognized when in hand, not whilst placing them, let alone ask info, that would not work either... (2 servers, first: additions work, second: additions do not work)
So, Im still hoping Mr Mason will elaborate this mechanics to the world.....

**Comment by MrKiller01** [comment]
After extensive searching, comparing, testing and testing again, I think I found a hint:


[config - Copy.yml.txt](https://github.com/marcelo-mason/PreciousStones/files/1887465/config.-.Copy.yml.txt)

This is my TP working config... You go figure it out yourself, I had a positive reaction at last, so I'm gonna test a bit more...
Thanks for all those who read this and found also no solution and never spoke up!

**Comment by frizzbee30** [comment]
If it's any help, meta-autoset was a nightmare for us, I removed it completely (no true or false)from the config, and it fixed a very similar issue to that you describe

**Comment by MrKiller01** [comment]
I have now more and better result, as I am having preciousstones.* as permission, I can place the TP stones (send/receive) give them a name and it works not for me and others with that same permission, but when i go lower in pex, it works without fault... Try it out....
I think therefor the mechanics is in that **bold** part (see below) 
`- title: TP (White)
  block: 95
  radius: 1
  custom-height: 4
  meta-name: '&bTransporter'
  meta-autoset: true
  meta-lore:
  - '&eTransporter, simply walk over when placed'
  - '&eIt covers an area of 1 radius'
  - '&eWith a max height of 4'
  - '&eEach additional Rank gains more'
  - '&e€100'
  limits:
  - 0
  - 4
  - 4
  - 10
  - 20
  - 250
  - 250
  **^teleport-on-entry: true**
  ?welcome-message: true
  ?farewell-message: true
  cuboid: true
  price: 100
- title: TP Reciever (Black)
  block: '95:15'
  radius: 1
  custom-height: 4
  meta-name: '&bTP Reciever'
  meta-autoset: true
  meta-lore:
  - '&eThis is the destination for your TP stone'
  - '&eIt covers an area of 1 radius'
  - '&eMUST have the same name as the TP'
  - '&ePoint at both then /ps setname xxx'
  - '&eEach additional Rank gains more'
  - '&e€100'
  limits:
  - 0
  - 4
  - 4
  - 10
  - 20
  - 250
  - 250
  **^teleport-destination: true**
  ?welcome-message: true
  ?farewell-message: true
  cuboid: true
  price: 100`
Oh, and maybe important, IDK, but I pasted those two blocks right under the last forresterblock... maybe that helped too

**Comment by MrKiller01** [comment]
Hi, so it looks like i'm talking (through my keyboard) with everybody except the one who can answer all the questions... Shame.... because at this time PS is generating more errors and conflict with Citizens' NPC's
The only thing I can do is remove the PS in the area where the NPC should be, select the NPC, /NPC TPHERE and place the PS back where it was....
But I sended Phaed two messages, but had no response at this time....
I hope he turns his computer on, one of these days....
