### ISSUE TITLE
Compatible issues

### ISSUE THREAD

**Issue by MrKiller01** [marcelo-mason/PreciousStones#1121]
Hi Phaed,
I hope you read this and are willing to consider action on this behalf...
I got this error 

> [16:05:12 ERROR]: Could not pass event BlockPlaceEvent to PreciousStones v10.7.2

org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:500) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:485) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlac
eEvent(CraftEventFactory.java:150) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620
]
        at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:207)
 [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractM
anager.java:505) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.jav
a:951) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseIt
em.java:37) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseIt
em.java:1) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:
13) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.
12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:
748) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:
406) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:
679) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.jav
a:577) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: br/net/fabiozumbi12/RedProtect/API/Re
dProtectAPI
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.RedProtectManager.c
anBuild(RedProtectManager.java:65) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.RedProtectManager.c
anBuildField(RedProtectManager.java:90) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.PermissionsManager.
canBuildField(PermissionsManager.java:160) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.ForceFieldManager.a
dd(ForceFieldManager.java:102) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.listeners.PSBlockListener.on
BlockPlace(PSBlockListener.java:740) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:302) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        ... 18 more
Caused by: java.lang.ClassNotFoundException: br.net.fabiozumbi12.RedProtect.API.
RedProtectAPI
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:152) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:100) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.RedProtectManager.c
anBuild(RedProtectManager.java:65) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.RedProtectManager.c
anBuildField(RedProtectManager.java:90) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.PermissionsManager.
canBuildField(PermissionsManager.java:160) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.ForceFieldManager.a
dd(ForceFieldManager.java:102) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.listeners.PSBlockListener.on
BlockPlace(PSBlockListener.java:740) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:302) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        ... 18 more

> 
This error came from my console after I decided to use Redprotect on selected worlds, unfortunately, PS did not like it being there and sticking its red nose in precious issues. 
I make it something to laugh about, i know, but I am amazed what you pluginmakers make, can make and understand it all, my sympathy you have, know that!! Is it possible for future versions to work together with RP? The owner of RedProtect is already being asked to look into this too, just I would like to see it being able to work on a selected number of worlds on one server.... Now i get errors and placed stones are not being recognized as Precious....
A shame really...
I hope you are willing to look into this, I know it makes me very happy, and it shows great competence on your behalf...

Thanks in advance....

**Comment by MrKiller01** [comment]
According to FabioZumbi12, owner of RedProtect, to whom I relayed this problem too, told me in a reaction that "PreciousStones need to update their hook with the latest public (or dev) builds of redprotect. The api changed since 7.3.0."
I hope you will find time to do this, software is not like bedrock, it is volatile and therefor it needs maintaining through several layers of updates.....
I hope You will take the time to help us all out....

Thanks...
