### ISSUE TITLE
PS on 1.13

### ISSUE THREAD

**Issue by andramil** [marcelo-mason/PreciousStones#1131]
Hi, 
I wannted to install PS on my 1.13 spigot server. I used 10.7.2 version. It didnt send any bgs on restart and is green in plugins list.

When i try to place cuboid i get this error:

`[00:25:07] [Server thread/ERROR]: Could not pass event BlockBreakEvent to PreciousStones v10.7.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[server.jar:git-Spigot-0b44fa0-1ef1ffd]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-0b44fa0-1ef1ffd]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[server.jar:git-Spigot-0b44fa0-1ef1ffd]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[server.jar:git-Spigot-0b44fa0-1ef1ffd]
	at net.minecraft.server.v1_13_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) ~[server.jar:git-Spigot-0b44fa0-1ef1ffd]
	at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:123) ~[server.jar:git-Spigot-0b44fa0-1ef1ffd]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1152) ~[server.jar:git-Spigot-0b44fa0-1ef1ffd]
	at net.minecraft.server.v1_13_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[server.jar:git-Spigot-0b44fa0-1ef1ffd]
	at net.minecraft.server.v1_13_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[server.jar:git-Spigot-0b44fa0-1ef1ffd]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[server.jar:git-Spigot-0b44fa0-1ef1ffd]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [server.jar:git-Spigot-0b44fa0-1ef1ffd]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [server.jar:git-Spigot-0b44fa0-1ef1ffd]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [server.jar:git-Spigot-0b44fa0-1ef1ffd]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [server.jar:git-Spigot-0b44fa0-1ef1ffd]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [server.jar:git-Spigot-0b44fa0-1ef1ffd]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.ItemStack.<init>(IISLjava/lang/Byte;)V
	at net.sacredlabyrinth.Phaed.PreciousStones.managers.ForceFieldManager.dropBlock(ForceFieldManager.java:2281) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.listeners.PSBlockListener.onBlockBreak(PSBlockListener.java:485) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[server.jar:git-Spigot-0b44fa0-1ef1ffd]
	... 17 more`

And of course there is no cuboida placed :(

**Comment by andramil** [comment]
I understand that 10.7.2 is for 1.12 version but will be there version for 1.13?
