### ISSUE TITLE
ERROR ver. 1.15.1

### ISSUE THREAD

**Issue by onietoja** [marcelo-mason/PreciousStones#1149]
Oh, Hi! I have a little problem. Server version is 1.15.1 :c Help, please :(

> [17:41:58] [Server thread/ERROR]: Error occurred while enabling PreciousStones v15.0 (Is it up to date?)
java.lang.NoClassDefFoundError: br/net/fabiozumbi12/RedProtect/Bukkit/RedProtect
	at net.sacredlabyrinth.Phaed.PreciousStones.managers.RedProtectManager.<init>(RedProtectManager.java:25) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.PreciousStones.onEnable(PreciousStones.java:151) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.1.jar:git-Spigot-492a779-9820cd2]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.15.1.jar:git-Spigot-492a779-9820cd2]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.15.1.jar:git-Spigot-492a779-9820cd2]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462) [spigot-1.15.1.jar:git-Spigot-492a779-9820cd2]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [spigot-1.15.1.jar:git-Spigot-492a779-9820cd2]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:456) [spigot-1.15.1.jar:git-Spigot-492a779-9820cd2]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot-1.15.1.jar:git-Spigot-492a779-9820cd2]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783) [spigot-1.15.1.jar:git-Spigot-492a779-9820cd2]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.ClassNotFoundException: br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot-1.15.1.jar:git-Spigot-492a779-9820cd2]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.15.1.jar:git-Spigot-492a779-9820cd2]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
	... 11 more

**Comment by onietoja** [comment]
what can i do?

**Comment by yannicklamprecht** [comment]
Add Redprotect plugin.
