### ISSUE TITLE
Could not pass event PlayerInteractEvent to PreciousStones v15.0

### ISSUE THREAD

**Issue by Asedi** [marcelo-mason/PreciousStones#1158]
`[14:51:16] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to PreciousStones v15.0
java.lang.NullPointerException: null
	at org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.getRelative(CraftBlock.java:249) ~[patched_1.15.2.jar:git-Paper-217]
	at org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.getRelative(CraftBlock.java:244) ~[patched_1.15.2.jar:git-Paper-217]
	at net.sacredlabyrinth.Phaed.PreciousStones.helpers.SignHelper.getAttachedBlock(SignHelper.java:49) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.listeners.PSPlayerListener.onPlayerInteract(PSPlayerListener.java:567) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor503.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-217]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-217]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-217]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-217]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[patched_1.15.2.jar:git-Paper-217]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:450) ~[patched_1.15.2.jar:git-Paper-217]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1379) ~[patched_1.15.2.jar:git-Paper-217]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-217]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-217]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-217]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-217]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-217]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-217]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-217]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1076) ~[patched_1.15.2.jar:git-Paper-217]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1069) ~[patched_1.15.2.jar:git-Paper-217]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-217]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1202) ~[patched_1.15.2.jar:git-Paper-217]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-217]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

Hello. When this error happens, server tps goes down to 10-11 and sometimes it even crashes. I'm using paper server engine.

**Comment by xtomyserrax** [comment]
Hey, it happens everytime you click a block or with which blocks?

I will check and try to fix it, but if you can, give me some explanation of what you do for this error to happen.

Thanks!

**Comment by xtomyserrax** [comment]
This issue has been fixed. Download it here: http://jenkins.elmakers.com/job/PreciousStones/33/net.sacredlabyrinth.Phaed$PreciousStones/

Thanks for the report! (if you can, please close this issue)

**Comment by Asedi** [comment]
Ohh... Sorry, I have forgotten about it... I appreciate all of your work, precious stones maintainers! Keep this plugin alive!

**Comment by xtomyserrax** [comment]
Thank you! If you find any other bug, please let us know! We are using now this repository: https://github.com/elBukkit/PreciousStones
