### ISSUE TITLE
ArmorStand damage event NPE

### ISSUE THREAD

**Issue by Htgan** [marcelo-mason/PreciousStones#819]
This happens when you put an armorstand in-between lava and water, purpose is to create a campfire looking thing with only the tip of the armorstand exposed above ground.

```
27.04 03:37:43 [Server] ERROR Could not pass event EntityDamageEvent to PreciousStones v9.8.3
27.04 03:37:43 [Server] INFO org.bukkit.event.EventException
27.04 03:37:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:86) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:539) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:525) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:590) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:576) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.EntityArmorStand.damageEntity(EntityArmorStand.java:383) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.Entity.burn(Entity.java:829) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.Entity.move(Entity.java:708) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.EntityLiving.g(EntityLiving.java:1338) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.EntityArmorStand.g(EntityArmorStand.java:495) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.EntityLiving.m(EntityLiving.java:1651) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.EntityLiving.t_(EntityLiving.java:1486) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.EntityArmorStand.t_(EntityArmorStand.java:500) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.World.entityJoinedWorld(World.java:1605) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.World.g(World.java:1580) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.World.tickEntities(World.java:1425) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.WorldServer.tickEntities(WorldServer.java:597) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:781) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
27.04 03:37:43 [Server] INFO Caused by: java.lang.NullPointerException
27.04 03:37:43 [Server] ERROR Could not pass event EntityDamageByBlockEvent to PreciousStones v9.8.3
27.04 03:37:43 [Server] INFO org.bukkit.event.EventException
27.04 03:37:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:86) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:460) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:590) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:576) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.EntityArmorStand.damageEntity(EntityArmorStand.java:383) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.Entity.burnFromLava(Entity.java:343) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.Entity.K(Entity.java:321) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.EntityLiving.K(EntityLiving.java:169) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.Entity.t_(Entity.java:246) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.EntityLiving.t_(EntityLiving.java:1447) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.EntityArmorStand.t_(EntityArmorStand.java:500) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.World.entityJoinedWorld(World.java:1605) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.World.g(World.java:1580) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.World.tickEntities(World.java:1425) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.WorldServer.tickEntities(WorldServer.java:597) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:781) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot18.jar:git-Spigot-1d14d5f-7aaa833]
27.04 03:37:43 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
27.04 03:37:43 [Server] INFO Caused by: java.lang.NullPointerException
```

**Comment by marcelo-mason** [comment]
Don't see any PreciousStones code being referenced.  Seems to be a problem elsewhere.
