### ISSUE TITLE
Command not recognized v9.8.3

### ISSUE THREAD

**Issue by dvargas135** [marcelo-mason/PreciousStones#841]
[15:26:09] [Server thread/INFO]: [PreciousStones] Enabling PreciousStones v9.8.3
[15:26:09] [Server thread/ERROR]: Error occurred while enabling PreciousStones v9.8.3 (Is it up to date?)
java.lang.NoSuchFieldError: SPRUCE_DOOR
	at net.sacredlabyrinth.Phaed.PreciousStones.MaterialName.getBlockMaterial(MaterialName.java:595) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.entries.BlockTypeEntry.<init>(BlockTypeEntry.java:76) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.Helper.toTypeEntriesBlind(Helper.java:644) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.FieldSettings.loadTypeEntries(FieldSettings.java:546) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.FieldSettings.parseSettings(FieldSettings.java:346) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.FieldSettings.<init>(FieldSettings.java:117) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.managers.SettingsManager.addForceFieldStones(SettingsManager.java:456) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.managers.SettingsManager.load(SettingsManager.java:338) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.managers.SettingsManager.<init>(SettingsManager.java:152) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.PreciousStones.onEnable(PreciousStones.java:133) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:286) [PlugMan.jar:?]
	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) [PlugMan.jar:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:104) [PlugMan.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]

**Comment by marcelo-mason** [comment]
Upgrading spigot to to 1.8 or downgrading PS will fix this issue.
