### ISSUE TITLE
Dynmap no longer draws fields (Jenkins build #527)

### ISSUE THREAD

**Issue by Zillew** [marcelo-mason/PreciousStones#864]
Hello,
I updated yesterday to build #527 on Jenkins. This caused the dynmap to stop drawing the fields, and gave this little gem:

"[Server thread/WARN]: [Dynmap-PreciousStones] Task #103 for Dynmap-PreciousStones v1.2.1 Release generated an exception
java.lang.NoClassDefFoundError: net/sacredlabyrinth/Phaed/PreciousStones/vectors/Field
	at net.dandielo.dynmap.preciousstones.layers.Fields.updateMarkerSet(Fields.java:404) ~[?:?]
	at net.dandielo.dynmap.preciousstones.layers.Fields.access$300(Fields.java:26) ~[?:?]
	at net.dandielo.dynmap.preciousstones.layers.Fields$Update.run(Fields.java:164) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.0-550ebac-7019900.jar.conf:git-Spigot-550ebac-7019900]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.0-550ebac-7019900.jar.conf:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot-1.8.0-550ebac-7019900.jar.conf:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.0-550ebac-7019900.jar.conf:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.0-550ebac-7019900.jar.conf:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.0-550ebac-7019900.jar.conf:git-Spigot-550ebac-7019900]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.ClassNotFoundException: net.sacredlabyrinth.Phaed.PreciousStones.vectors.Field
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_79]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_79]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_79]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_79]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.0-550ebac-7019900.jar.conf:git-Spigot-550ebac-7019900]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.0-550ebac-7019900.jar.conf:git-Spigot-550ebac-7019900]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_79]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_79]
	... 10 more"
Is there anything you could do from your end to fix this? I have tried contacting the new author of the Dynmap-PreciousStones but have not yet received a reply...

Also: Running build 1.2.2 (latest) of the dynmap-PS plugin. 

Thanks!

**Comment by marcelo-mason** [comment]
Updated it and added the project to my Jenkins.

**Comment by Zillew** [comment]
Thanks for the quick reply!
I tested and got this:
11.07 10:05:30 [Server] INFO ... 6 more 11.07 10:05:30 [Server] INFO Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml 11.07 10:05:30 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79] 11.07 10:05:30 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-1.8.0-550ebac-7019900T.jar:git-Spigot-550ebac-7019900] 11.07 10:05:30 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152) [spigot-1.8.0-550ebac-7019900T.jar:git-Spigot-550ebac-7019900] 11.07 10:05:30 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:291) [spigot-1.8.0-550ebac-7019900T.jar:git-Spigot-550ebac-7019900] 11.07 10:05:30 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.8.0-550ebac-7019900T.jar:git-Spigot-550ebac-7019900] 11.07 10:05:30 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:154) ~[spigot-1.8.0-550ebac-7019900T.jar:git-Spigot-550ebac-7019900] 11.07 10:05:30 [Server] INFO org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml 11.07 10:05:30 [Server] ERROR Could not load 'plugins/Dynmap-PreciousStones.jar' in folder 'plugins'

**Comment by marcelo-mason** [comment]
hmmmmmmmmmm.  Ok gonna check this out.

**Comment by Zillew** [comment]
Thanks for yet again, another quick answer! :) :+1:
