### ISSUE TITLE
Could not pass event PlayerMoveEvent to PreciousStones v10.0.3  (Spigot 1.8.8)

### ISSUE THREAD

**Issue by ReNNoN** [marcelo-mason/PreciousStones#889]
```
[13:01:11] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to PreciousStones v10.0.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270) [Spigot.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [Spigot.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [Spigot.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-0359393-9cd1111]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Spigot.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [Spigot.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [Spigot.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [Spigot.jar:git-Spigot-0359393-9cd1111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Matcher.java:857) ~[?:1.8.0_60]
	at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_60]
	at java.lang.String.replaceAll(String.java:2223) ~[?:1.8.0_60]
	at net.sacredlabyrinth.Phaed.PreciousStones.helpers.ChatHelper.replaceFormatting(ChatHelper.java:988) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.helpers.ChatHelper.format(ChatHelper.java:946) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.helpers.ChatHelper.send(ChatHelper.java:768) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.managers.CommunicationManager.showWelcomeMessage(CommunicationManager.java:2263) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.managers.EntryManager.enterOverlappedArea(EntryManager.java:413) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.listeners.PSPlayerListener.onPlayerMove(PSPlayerListener.java:423) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-0359393-9cd1111]
	... 15 more
```

-------------------------------------------------------
how to solve this?

thanks!

**Comment by marcelo-mason** [comment]
Looks like a prob with the *enteringNamedField* string in the language.xml,  did you change it?
