### ISSUE TITLE
Copy - paste Precious Stones

### ISSUE THREAD

**Issue by MrKiller01** [marcelo-mason/PreciousStones#924]
When copying an area where a precious stone 'city' is placed, and works when visualizing it, why can't i just copy the whole area and past it somewhere else and when i ask again for the visualization of the defined area, it says: You are not inside of a field! yet i can almost touch the stone with my eyeballs!!!! (i only have to blink to touch them, that close i am!)   
Oh, you want to know.....
-Spigot MC 1.8 Worldguard, Worldedit, PermissionsEx, and 40 or so plugins more...
Oh, it did work, almost a half year and several adjustments ago... Ask me...

**Comment by marcelo-mason** [comment]
How are you copying it?  PS fields are stored on the database with explicit coordinates, if you copy the area and block via worldedit or something, the field doesn't really get moved, its still in the old spot in the database.  You need to break the field, copy the stuff, then put it back.

**Comment by MrKiller01** [comment]
Oh, then it is a wonder that it worked earlier.....

**Comment by MrKiller01** [comment]
I pulled this from the console, upon my action, in the last part all my plugins...

[23:19:22 ERROR]: Could not pass event BlockBreakEvent to PreciousStones v10.0.4

org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:310) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.breakBlock(PlayerI
nteractManager.java:286) [spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractMa
nager.java:121) [spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java
:623) [spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [s
pigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [s
pigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:1
3) [spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8
.8.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
15) [spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
74) [spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
54) [spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:557) [spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.ForceFieldManager.d
ropFieldBlock(ForceFieldManager.java:2556) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.ForceFieldManager.d
ropField(ForceFieldManager.java:2542) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.ForceFieldManager.f
lush(ForceFieldManager.java:2530) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.ForceFieldManager.d
eleteField(ForceFieldManager.java:588) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.ForceFieldManager.r
elease(ForceFieldManager.java:2484) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.ForceFieldManager.d
eleteField(ForceFieldManager.java:595) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.ForceFieldManager.r
elease(ForceFieldManager.java:2484) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.managers.ForceFieldManager.r
elease(ForceFieldManager.java:2472) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.listeners.PSBlockListener.re
moveAndRefundBlock(PSBlockListener.java:690) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.listeners.PSBlockListener.br
eakingFieldChecks(PSBlockListener.java:675) ~[?:?]
        at net.sacredlabyrinth.Phaed.PreciousStones.listeners.PSBlockListener.on
BlockBreak(PSBlockListener.java:429) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor246.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_66]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        ... 17 more
[23:19:35 INFO]: Mr_Killer01 issued server command: /up 1
[23:19:48 ERROR]: Error at SQL INSERT Query: java.sql.SQLException: columns x, y
, z, world are not unique
[23:34:10 INFO]: Mr_Killer01 issued server command: /ps visualize
>pl
[23:40:14 INFO]: Plugins (38): dynmap, WorldEdit, Spawnx, OpenInv, BlockLocker,
Lift, ClearLag, PluginManagerReloaded, SmartSpawn, AnimalPlague, WorldBorder, Ho
lographicDisplays, Torture, StopSpam, WorldGuard, SimpleBackup, ServerMotd, Perm
issionsEx, mcMMO, ActionAnnouncer, Vault, DPets, RealTime, WirelessRedstone, Cas
inoSlots, AreaShop, Essentials, Jobs, MobArena, PreciousStones, SignShop, mcMMO-
WorldGuard, OnTime, EssentialsChat, SignShopHotel, TitleManager, MobHunting, Mys
qlEconomyBank

**Comment by MrKiller01** [comment]
I am taking Marcello's advise and close this.... Thanks for reacting so quickly....
