### ISSUE TITLE
Exception error in console

### ISSUE THREAD

**Issue by MrKiller01** [marcelo-mason/PreciousStones#939]
I have a question about this error i get when using server spigot on MC 1.9
`[21:04:43 WARN]: Exception in thread "Craft Scheduler Thread - 336"
[21:04:43 WARN]: org.apache.commons.lang.UnhandledException: Plugin PreciousSton
es v10.0.4 generated an exception while executing task 15397
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lor
g/bukkit/entity/Player;
        at ps.org.mcstats.Metrics.postPlugin(Metrics.java:363)
        at ps.org.mcstats.Metrics.access$500(Metrics.java:68)
        at ps.org.mcstats.Metrics$1.run(Metrics.java:255)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java
:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:53)
        ... 3 more

[21:09:16 WARN]: Exception in thread "Craft Scheduler Thread - 352"
[21:09:16 WARN]: org.apache.commons.lang.UnhandledException: Plugin EMetrics v0.
0.4 generated an exception while executing task 9
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lor
g/bukkit/entity/Player;
        at com.gmail.nossr50.metrics.mcstats.Metrics.postPlugin(Metrics.java:502
)
        at com.gmail.nossr50.metrics.mcstats.Metrics.access$500(Metrics.java:45)

        at com.gmail.nossr50.metrics.mcstats.Metrics$1.run(Metrics.java:353)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java
:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:53)
        ... 3 more

[21:09:16 WARN]: Exception in thread "Craft Scheduler Thread - 359"
[21:09:16 WARN]: org.apache.commons.lang.UnhandledException: Plugin Spawnx v1.6
generated an exception while executing task 14
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lor
g/bukkit/entity/Player;
        at me.xtomyserrax.Spawnx.Metrics.postPlugin(Metrics.java:308)
        at me.xtomyserrax.Spawnx.Metrics.access$4(Metrics.java:301)
        at me.xtomyserrax.Spawnx.Metrics$1.run(Metrics.java:196)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java
:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:53)
        ... 3 more

[21:09:16 WARN]: Exception in thread "Craft Scheduler Thread - 358"
[21:09:16 WARN]: org.apache.commons.lang.UnhandledException: Plugin AreaShop v2.
2.1 generated an exception while executing task 38
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lor
g/bukkit/entity/Player;
        at nl.evolutioncoding.areashop.Metrics.postPlugin(Metrics.java:336)
        at nl.evolutioncoding.areashop.Metrics.access$4(Metrics.java:328)
        at nl.evolutioncoding.areashop.Metrics$1.run(Metrics.java:223)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java
:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:53)
        ... 3 more

[21:14:44 WARN]: Exception in thread "Craft Scheduler Thread - 356"
[21:14:44 WARN]: org.apache.commons.lang.UnhandledException: Plugin PreciousSton
es v10.0.4 generated an exception while executing task 15397
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lor
g/bukkit/entity/Player;
        at ps.org.mcstats.Metrics.postPlugin(Metrics.java:363)
        at ps.org.mcstats.Metrics.access$500(Metrics.java:68)
        at ps.org.mcstats.Metrics$1.run(Metrics.java:255)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java
:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:53)
        ... 3 more
`
I know that it is not all your plugin, but you might want to look at it...

Thanks

**Comment by marcelo-mason** [comment]
Taking a look.

**Comment by MrKiller01** [comment]
You're a rock!

**Comment by marcelo-mason** [comment]
1.9 compatible version building in Jenkins
