### ISSUE TITLE
Another bump in the cable PreciousStones plugin

### ISSUE THREAD

**Issue by MrKiller01** [marcelo-mason/PreciousStones#940]
Hi,

I know you did make a change in the plugin yesterday, but the console is still spewing some messages.
`[11:42:01 WARN]: Exception in thread "Craft Scheduler Thread - 1517"
[11:42:01 WARN]: org.apache.commons.lang.UnhandledException: Plugin PreciousSton
es v10.0.4 generated an exception while executing task 25988
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lor
g/bukkit/entity/Player;
        at ps.org.mcstats.Metrics.postPlugin(Metrics.java:363)
        at ps.org.mcstats.Metrics.access$500(Metrics.java:68)
        at ps.org.mcstats.Metrics$1.run(Metrics.java:255)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java
:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:53)
        ... 3 more` 

You know how much we appreciate this, if my paypal is working (just started it) i'll sure donate some money to encourage you....
Thanks...

**Comment by marcelo-mason** [comment]
You're still on PS 10.4.0.  Download PS 10.1.0 from my Jenkins.

**Comment by DooKid** [comment]
I'm still getting: [13:11:18 WARN]: Exception in thread "Craft Scheduler Thread - 48" 
[13:11:18 WARN]: org.apache.commons.lang.UnhandledException: Plugin PreciousStones v10.0.5 generated an exception while executing task 575
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at ps.org.mcstats.Metrics.postPlugin(Metrics.java:363)
	at ps.org.mcstats.Metrics.access$500(Metrics.java:68)
	at ps.org.mcstats.Metrics$1.run(Metrics.java:255)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more 

With the last build of ps and last build of spigot 1.9.
