### ISSUE TITLE
Godstone did work 2 versions before...

### ISSUE THREAD

**Issue by MrKiller01** [marcelo-mason/PreciousStones#950]
I use an emerald block for godstone. When i earlier talked about it with you, it worked nicely, i think that it was under 1.8.8 but i am not sure. Try for yourself, the feeding still works, the repair does not, not the armour nor the weapons... I will start a clean server and put the latest PreciousStones in there and see if that works... I'll be back!

**Comment by MrKiller01** [comment]
I just finished using only PreciousStones in a clean world and no other plugins... It works ok...
Strange that interference of something else is rendering a part of Godstone inoperable... The flags are good by the way, so, i do not like putting plugins piece by piece in this clean install and see where it goes wrong, but, i will do that, tomorrow.!

**Comment by MrKiller01** [comment]
Well, i tried every plugin, and even when i put the latest in it worked, and now the world i had, yep, that did not work sadly. So it must be something in the world i use, i can't find anything what i could do to change it, i hope you have a suggestion...

**Comment by MrKiller01** [comment]
I am now restoring a backup from december 2015 and put the world in it's place, let's see if that makes a difference.

**Comment by MrKiller01** [comment]
Definitely it's in the map, the one i restored was completely empty and i took care of signs, areashop, etc even permissions. But that last one had no rights to use this stone, so i put the config file of PermissionsEx in the folder and restarted. This time it recognized me as one that may heal and repair, the same permission.yml file as on my normal server. Now i think, could something in the map interfere in the repair action the stone should give? Only ~Feeding~ works....

**Comment by MrKiller01** [comment]
I do not know how to solve this problem, it only occurs when i use my map, i even tried my map with three plugins (PS, PermissionsEx and Essentials), no success. If I use an older map, it seems to work, now, tomorrow i mean, i go back in time (not really) and retrace my steps from there, even if it is an almost impossible undertaking, forseeing the size and amount of the in-world changes (700Mb)...

**Comment by MrKiller01** [comment]
Ok, now i've done things backwards, i took the current map from 1.9 latest version, copied it to a MC 1.8.8 version of Spigot, and there the healing, repairing and feeding worked as it should do in 1.9
Maybe this will give a hint to solve this problem...

**Comment by marcelo-mason** [comment]
Are you using the default mushroom block for the GodStone?  I think that's what stopped working.

**Comment by MrKiller01** [comment]
I just started a fresh server, 1.9.2 and put the latest spigot build in the folder and started the server with only Precious Stones.... Does not work.
`
E:\GAMES\MINECRAFT-SERVERS\TEST-SERVER>java -Xmx1024M -Xms1024M -jar spigot.jar
nogui
Loading libraries, please wait...
[15:49:38 INFO]: Starting minecraft server version 1.9
[15:49:38 INFO]: Loading properties
[15:49:38 INFO]: Default game type: SURVIVAL
[15:49:38 INFO]: This server is running CraftBukkit version git-Spigot-d20369f-7
fc5cd8 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
[15:49:38 INFO]: Debug logging is disabled
[15:49:38 INFO]: Server Ping Player Sample Count: 12
[15:49:38 INFO]: Using 4 threads for Netty based IO
[15:49:38 INFO]: Generating keypair
[15:49:38 INFO]: Starting Minecraft server on *:25565
[15:49:38 INFO]: Using default channel type
[15:49:39 INFO]: Set PluginClassLoader as parallel capable
[15:49:39 INFO]: [PreciousStones] Loading PreciousStones v10.0.4
[15:49:39 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[15:49:39 INFO]: Preparing level "world"
[15:49:39 INFO]: -------- World Settings For [world] --------
[15:49:39 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[15:49:39 INFO]: Arrow Despawn Rate: 1200
[15:49:39 INFO]: Item Merge Radius: 2.5
[15:49:39 INFO]: Item Despawn Rate: 6000
[15:49:39 INFO]: View Distance: 10
[15:49:39 INFO]: Max Entity Collisions: 8
[15:49:39 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[15:49:39 INFO]: Zombie Aggressive Towards Villager: true
[15:49:39 INFO]: Mob Spawn Range: 4
[15:49:39 INFO]: Nerfing mobs spawned from spawners: false
[15:49:39 INFO]: Cactus Growth Modifier: 100%
[15:49:39 INFO]: Cane Growth Modifier: 100%
[15:49:39 INFO]: Melon Growth Modifier: 100%
[15:49:39 INFO]: Mushroom Growth Modifier: 100%
[15:49:39 INFO]: Pumpkin Growth Modifier: 100%
[15:49:39 INFO]: Sapling Growth Modifier: 100%
[15:49:39 INFO]: Wheat Growth Modifier: 100%
[15:49:39 INFO]: NetherWart Growth Modifier: 100%
[15:49:39 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[15:49:39 INFO]: Max TNT Explosions: 100
[15:49:39 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[15:49:39 INFO]: Structure Info Saving: true
[15:49:39 INFO]: Random Lighting Updates: false
[15:49:39 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[15:49:39 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64

[15:49:39 INFO]: Experience Merge Radius: 3.0
[15:49:39 INFO]: -------- World Settings For [world_nether] --------
[15:49:39 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[15:49:39 INFO]: Arrow Despawn Rate: 1200
[15:49:39 INFO]: Item Merge Radius: 2.5
[15:49:39 INFO]: Item Despawn Rate: 6000
[15:49:39 INFO]: View Distance: 10
[15:49:39 INFO]: Max Entity Collisions: 8
[15:49:39 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[15:49:39 INFO]: Zombie Aggressive Towards Villager: true
[15:49:39 INFO]: Mob Spawn Range: 4
[15:49:39 INFO]: Nerfing mobs spawned from spawners: false
[15:49:39 INFO]: Cactus Growth Modifier: 100%
[15:49:39 INFO]: Cane Growth Modifier: 100%
[15:49:39 INFO]: Melon Growth Modifier: 100%
[15:49:39 INFO]: Mushroom Growth Modifier: 100%
[15:49:39 INFO]: Pumpkin Growth Modifier: 100%
[15:49:39 INFO]: Sapling Growth Modifier: 100%
[15:49:39 INFO]: Wheat Growth Modifier: 100%
[15:49:39 INFO]: NetherWart Growth Modifier: 100%
[15:49:39 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[15:49:39 INFO]: Max TNT Explosions: 100
[15:49:39 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[15:49:39 INFO]: Structure Info Saving: true
[15:49:39 INFO]: Random Lighting Updates: false
[15:49:39 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[15:49:39 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64

[15:49:39 INFO]: Experience Merge Radius: 3.0
[15:49:39 INFO]: -------- World Settings For [world_the_end] --------
[15:49:39 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[15:49:39 INFO]: Arrow Despawn Rate: 1200
[15:49:39 INFO]: Item Merge Radius: 2.5
[15:49:39 INFO]: Item Despawn Rate: 6000
[15:49:39 INFO]: View Distance: 10
[15:49:39 INFO]: Max Entity Collisions: 8
[15:49:39 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[15:49:39 INFO]: Zombie Aggressive Towards Villager: true
[15:49:39 INFO]: Mob Spawn Range: 4
[15:49:39 INFO]: Nerfing mobs spawned from spawners: false
[15:49:39 INFO]: Cactus Growth Modifier: 100%
[15:49:39 INFO]: Cane Growth Modifier: 100%
[15:49:39 INFO]: Melon Growth Modifier: 100%
[15:49:39 INFO]: Mushroom Growth Modifier: 100%
[15:49:39 INFO]: Pumpkin Growth Modifier: 100%
[15:49:39 INFO]: Sapling Growth Modifier: 100%
[15:49:39 INFO]: Wheat Growth Modifier: 100%
[15:49:39 INFO]: NetherWart Growth Modifier: 100%
[15:49:39 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[15:49:39 INFO]: Max TNT Explosions: 100
[15:49:39 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[15:49:39 INFO]: Structure Info Saving: true
[15:49:39 INFO]: Random Lighting Updates: false
[15:49:39 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[15:49:39 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64

[15:49:39 INFO]: Experience Merge Radius: 3.0
[15:49:39 INFO]: Preparing start region for level 0 (Seed: -777638682466465786)
[15:49:40 INFO]: Preparing spawn area: 95%
[15:49:40 INFO]: Preparing start region for level 1 (Seed: -777638682466465786)
[15:49:41 INFO]: Preparing start region for level 2 (Seed: -777638682466465786)
[15:49:41 INFO]: [PreciousStones] Enabling PreciousStones v10.0.4
[15:49:41 INFO]: [PreciousStones] Version 10.0.4 loaded
[15:49:41 INFO]: [PreciousStones] SQLite Connection successful
[15:49:41 INFO]: [PreciousStones] Creating table: pstone_cuboids
[15:49:42 INFO]: [PreciousStones] Creating table: pstone_fields
[15:49:42 INFO]: [PreciousStones] Creating table: pstone_unbreakables
[15:49:42 INFO]: [PreciousStones] Creating table: pstone_grief_undo
[15:49:42 INFO]: [PreciousStones] Creating table: pstone_translocations
[15:49:43 INFO]: [PreciousStones] Creating table: pstone_storedblocks
[15:49:43 INFO]: [PreciousStones] Creating table: pstone_players
[15:49:43 INFO]: [PreciousStones] Creating table: pstone_snitches
[15:49:45 INFO]: [PreciousStones] Added new indexes to database
[15:49:45 INFO]: [PreciousStones] Creating table: pstone_purchase_payments
[15:49:45 INFO]: [PreciousStones] Added new indexes to database
[15:49:46 INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:49:46 INFO]: Done (6,691s)! For help, type "help" or "?"
[15:49:46 WARN]: Exception in thread "Craft Scheduler Thread - 1"
[15:49:46 WARN]: org.apache.commons.lang.UnhandledException: Plugin PreciousSton
es v10.0.4 generated an exception while executing task 5
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lor
g/bukkit/entity/Player;
        at ps.org.mcstats.Metrics.postPlugin(Metrics.java:363)
        at ps.org.mcstats.Metrics.access$500(Metrics.java:68)
        at ps.org.mcstats.Metrics$1.run(Metrics.java:255)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java
:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:53)
        ... 3 more

>
`
This here above was the response on the console..., and after a while i had picked this from the console, it keeps generating errors.
`E:\GAMES\MINECRAFT-SERVERS\TEST-SERVER>java -Xmx1024M -Xms1024M -jar spigot.jar
nogui
Loading libraries, please wait...
[16:52:53 INFO]: Starting minecraft server version 1.9
[16:52:53 INFO]: Loading properties
[16:52:53 INFO]: Default game type: SURVIVAL
[16:52:54 INFO]: This server is running CraftBukkit version git-Spigot-d20369f-7
fc5cd8 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
[16:52:54 INFO]: Debug logging is disabled
[16:52:54 INFO]: Server Ping Player Sample Count: 12
[16:52:54 INFO]: Using 4 threads for Netty based IO
[16:52:54 INFO]: Generating keypair
[16:52:54 INFO]: Starting Minecraft server on *:25565
[16:52:54 INFO]: Using default channel type
[16:52:54 INFO]: Set PluginClassLoader as parallel capable
[16:52:54 INFO]: [PreciousStones] Loading PreciousStones v10.0.4
[16:52:54 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[16:52:54 INFO]: Preparing level "world"
[16:52:54 INFO]: -------- World Settings For [world] --------
[16:52:54 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[16:52:54 INFO]: View Distance: 10
[16:52:54 INFO]: Item Despawn Rate: 6000
[16:52:54 INFO]: Item Merge Radius: 2.5
[16:52:54 INFO]: Arrow Despawn Rate: 1200
[16:52:54 INFO]: Zombie Aggressive Towards Villager: true
[16:52:54 INFO]: Max Entity Collisions: 8
[16:52:54 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[16:52:54 INFO]: Nerfing mobs spawned from spawners: false
[16:52:54 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[16:52:54 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[16:52:54 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64

[16:52:54 INFO]: Mob Spawn Range: 4
[16:52:54 INFO]: Random Lighting Updates: false
[16:52:54 INFO]: Max TNT Explosions: 100
[16:52:54 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[16:52:54 INFO]: Cactus Growth Modifier: 100%
[16:52:54 INFO]: Cane Growth Modifier: 100%
[16:52:54 INFO]: Melon Growth Modifier: 100%
[16:52:54 INFO]: Mushroom Growth Modifier: 100%
[16:52:54 INFO]: Pumpkin Growth Modifier: 100%
[16:52:54 INFO]: Sapling Growth Modifier: 100%
[16:52:54 INFO]: Wheat Growth Modifier: 100%
[16:52:54 INFO]: NetherWart Growth Modifier: 100%
[16:52:54 INFO]: Structure Info Saving: true
[16:52:54 INFO]: Experience Merge Radius: 3.0
[16:52:54 INFO]: -------- World Settings For [world_nether] --------
[16:52:54 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[16:52:54 INFO]: View Distance: 10
[16:52:54 INFO]: Item Despawn Rate: 6000
[16:52:54 INFO]: Item Merge Radius: 2.5
[16:52:54 INFO]: Arrow Despawn Rate: 1200
[16:52:54 INFO]: Zombie Aggressive Towards Villager: true
[16:52:54 INFO]: Max Entity Collisions: 8
[16:52:54 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[16:52:54 INFO]: Nerfing mobs spawned from spawners: false
[16:52:54 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[16:52:54 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[16:52:54 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64

[16:52:54 INFO]: Mob Spawn Range: 4
[16:52:54 INFO]: Random Lighting Updates: false
[16:52:54 INFO]: Max TNT Explosions: 100
[16:52:54 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[16:52:54 INFO]: Cactus Growth Modifier: 100%
[16:52:54 INFO]: Cane Growth Modifier: 100%
[16:52:54 INFO]: Melon Growth Modifier: 100%
[16:52:54 INFO]: Mushroom Growth Modifier: 100%
[16:52:54 INFO]: Pumpkin Growth Modifier: 100%
[16:52:54 INFO]: Sapling Growth Modifier: 100%
[16:52:54 INFO]: Wheat Growth Modifier: 100%
[16:52:54 INFO]: NetherWart Growth Modifier: 100%
[16:52:54 INFO]: Structure Info Saving: true
[16:52:54 INFO]: Experience Merge Radius: 3.0
[16:52:54 INFO]: -------- World Settings For [world_the_end] --------
[16:52:54 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[16:52:54 INFO]: View Distance: 10
[16:52:54 INFO]: Item Despawn Rate: 6000
[16:52:54 INFO]: Item Merge Radius: 2.5
[16:52:54 INFO]: Arrow Despawn Rate: 1200
[16:52:54 INFO]: Zombie Aggressive Towards Villager: true
[16:52:54 INFO]: Max Entity Collisions: 8
[16:52:54 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[16:52:54 INFO]: Nerfing mobs spawned from spawners: false
[16:52:54 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[16:52:54 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[16:52:54 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64

[16:52:54 INFO]: Mob Spawn Range: 4
[16:52:54 INFO]: Random Lighting Updates: false
[16:52:54 INFO]: Max TNT Explosions: 100
[16:52:54 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[16:52:54 INFO]: Cactus Growth Modifier: 100%
[16:52:54 INFO]: Cane Growth Modifier: 100%
[16:52:54 INFO]: Melon Growth Modifier: 100%
[16:52:54 INFO]: Mushroom Growth Modifier: 100%
[16:52:54 INFO]: Pumpkin Growth Modifier: 100%
[16:52:54 INFO]: Sapling Growth Modifier: 100%
[16:52:54 INFO]: Wheat Growth Modifier: 100%
[16:52:54 INFO]: NetherWart Growth Modifier: 100%
[16:52:54 INFO]: Structure Info Saving: true
[16:52:54 INFO]: Experience Merge Radius: 3.0
[16:52:55 INFO]: Preparing start region for level 0 (Seed: -777638682466465786)
[16:52:56 INFO]: Preparing spawn area: 78%
[16:52:56 INFO]: Preparing start region for level 1 (Seed: -777638682466465786)
[16:52:56 INFO]: Preparing start region for level 2 (Seed: -777638682466465786)
[16:52:56 INFO]: [PreciousStones] Enabling PreciousStones v10.0.4
[16:52:56 INFO]: [PreciousStones] Version 10.0.4 loaded
[16:52:57 INFO]: [PreciousStones] SQLite Connection successful
[16:52:57 INFO]: Server permissions file permissions.yml is empty, ignoring it
[16:52:57 INFO]: Done (2,852s)! For help, type "help" or "?"
[16:52:57 WARN]: Exception in thread "Craft Scheduler Thread - 1"
[16:52:57 WARN]: org.apache.commons.lang.UnhandledException: Plugin PreciousSton
es v10.0.4 generated an exception while executing task 5
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lor
g/bukkit/entity/Player;
        at ps.org.mcstats.Metrics.postPlugin(Metrics.java:363)
        at ps.org.mcstats.Metrics.access$500(Metrics.java:68)
        at ps.org.mcstats.Metrics$1.run(Metrics.java:255)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java
:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:53)
        ... 3 more

[16:53:30 INFO]: UUID of player Mr_Killer01 is b0bc2f19-d503-4f14-b8d8-4cce5c515
3a6
[16:53:31 INFO]: Mr_Killer01[/10.11.20.110:56679] logged in with entity id 42 at
 ([world]-253.10297407273015, 69.0, 220.93643420109814)
[16:56:18 INFO]: Mr_Killer01 has just earned the achievement [Time to Mine!]
[16:56:18 INFO]: Mr_Killer01 has just earned the achievement [Getting an Upgrade
]
[17:02:57 WARN]: Exception in thread "Craft Scheduler Thread - 4"
[17:02:57 WARN]: org.apache.commons.lang.UnhandledException: Plugin PreciousSton
es v10.0.4 generated an exception while executing task 5
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lor
g/bukkit/entity/Player;
        at ps.org.mcstats.Metrics.postPlugin(Metrics.java:363)
        at ps.org.mcstats.Metrics.access$500(Metrics.java:68)
        at ps.org.mcstats.Metrics$1.run(Metrics.java:255)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java
:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:53)
        ... 3 more

[17:05:08 INFO]: Mr_Killer01 has just earned the achievement [Hot Topic]
[17:12:58 WARN]: Exception in thread "Craft Scheduler Thread - 6"
[17:12:58 WARN]: org.apache.commons.lang.UnhandledException: Plugin PreciousSton
es v10.0.4 generated an exception while executing task 5
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lor
g/bukkit/entity/Player;
        at ps.org.mcstats.Metrics.postPlugin(Metrics.java:363)
        at ps.org.mcstats.Metrics.access$500(Metrics.java:68)
        at ps.org.mcstats.Metrics$1.run(Metrics.java:255)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java
:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:53)
        ... 3 more

[17:22:58 WARN]: Exception in thread "Craft Scheduler Thread - 8"
[17:22:58 WARN]: org.apache.commons.lang.UnhandledException: Plugin PreciousSton
es v10.0.4 generated an exception while executing task 5
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lor
g/bukkit/entity/Player;
        at ps.org.mcstats.Metrics.postPlugin(Metrics.java:363)
        at ps.org.mcstats.Metrics.access$500(Metrics.java:68)
        at ps.org.mcstats.Metrics$1.run(Metrics.java:255)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java
:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:53)
        ... 3 more

[17:26:00 INFO]: Mr_Killer01 has just earned the achievement [Acquire Hardware]
[17:32:59 WARN]: Exception in thread "Craft Scheduler Thread - 10"
[17:32:59 WARN]: org.apache.commons.lang.UnhandledException: Plugin PreciousSton
es v10.0.4 generated an exception while executing task 5
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lor
g/bukkit/entity/Player;
        at ps.org.mcstats.Metrics.postPlugin(Metrics.java:363)
        at ps.org.mcstats.Metrics.access$500(Metrics.java:68)
        at ps.org.mcstats.Metrics$1.run(Metrics.java:255)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java
:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:53)
        ... 3 more

[17:42:59 WARN]: Exception in thread "Craft Scheduler Thread - 12"
[17:42:59 WARN]: org.apache.commons.lang.UnhandledException: Plugin PreciousSton
es v10.0.4 generated an exception while executing task 5
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lor
g/bukkit/entity/Player;
        at ps.org.mcstats.Metrics.postPlugin(Metrics.java:363)
        at ps.org.mcstats.Metrics.access$500(Metrics.java:68)
        at ps.org.mcstats.Metrics$1.run(Metrics.java:255)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java
:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:53)
        ... 3 more

[17:53:00 WARN]: Exception in thread "Craft Scheduler Thread - 14"
[17:53:00 WARN]: org.apache.commons.lang.UnhandledException: Plugin PreciousSton
es v10.0.4 generated an exception while executing task 5
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lor
g/bukkit/entity/Player;
        at ps.org.mcstats.Metrics.postPlugin(Metrics.java:363)
        at ps.org.mcstats.Metrics.access$500(Metrics.java:68)
        at ps.org.mcstats.Metrics$1.run(Metrics.java:255)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java
:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:53)
        ... 3 more

>`
Now i'm about to cheat a godstone in my survivalgame, see how that works...
Well, i gave myself a Emerald block, because destroying a brown mushroomblock results in a mushroom and not a block. This way i see when i pick it up that i actually have picked up a Godstone!
I guess there is something wrong.....

**Comment by marcelo-mason** [comment]
Pick up the latest version of PS from Jenkins.

**Comment by MrKiller01** [comment]
Do you have a direct link? because when i try to find it i always end up downloading the wrong one...

Thanks

**Comment by MrKiller01** [comment]
Well, i did not get that, so i obviously went to Jenkins ans saw that there was a 10.1.3 version released, but again, it does not repair and still says 10.1.1. I know how tiresome this can be, but hey, i have patience so that you can fix things in a timely manner. Let me know if there is something i can do for you to help testing, setting up a totally clean server with only your plugin is no problem for me, happy to help... Let me know...

**Comment by MrKiller01** [comment]
Oh, just to be very clear, you told me about the mushroomblock, and normally when this plugin is activated, all metaset-auto blocks are changed. That is not the case with me. So i would love to use the original configured block to test, was it not that if i put a mushroom block on the ground, it says nothing, unless i destroy it, then it becomes the block i need, except the breaking of mushroom, which gives a little mushroom and no block. Thought you might wanted to know that...

**Comment by marcelo-mason** [comment]
Mushrooms no longer working as pstones for some reason.  Change block type.

**Comment by MrKiller01** [comment]
I did not use the mushroom block, i stumbled upon that error behaviour a few weeks ago. Is there a possibility the next update does repair close to a godstone? or must we simply forget that?

**Comment by MrKiller01** [comment]
Yesterday i updated my spigot version, again, and after doing so a few moments back, suddenly it repaired!!!!!!!!!
This server is running CraftBukkit version git-Spigot-944aa20-8cb1b36 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)
Today's version worked
So, thanks for all your hard work, it finally does what it must do

**Comment by MrKiller01** [comment]
Strangely, the second server i was setting up had also PS installed on it, but there it only feeds and heals..... strange, server 1 with almost 40 plugins runs as it should and server 2 with Plugins (10): PermissionsEx, PluginManager, SimpleBackup, WorldEdit, Vault, Multiverse-Core, WorldGuard, WorldEditSelectionVisualizer, Essentials and PreciousStones does only two third of the action...
>

**Comment by MrKiller01** [comment]
Hello! I keep wondering how many things would go wrong on my server..... or even could go wrong, but some things keep working like they should, others switch from day 1 it is working until day 3 when it decides to stop working. I wish i could do something for the maker(s) to test out some of their theories. I am a little sad that the repair function does not work, whilst i have places made in my world where peeps can go to and pay a diamond to get access to this block that should repair.... It should, but it doesn't again anymore... I am almost positive if i disable all plugins except PS that it wouldn't work either....
I did this before... 
I hope to hear from you soon....

Thanks..
