### ISSUE TITLE
Error on start and while running latest Spigot

### ISSUE THREAD

**Issue by donotshake** [marcelo-mason/PreciousStones#951]
[16:22:17 WARN]: org.apache.commons.lang.UnhandledException: Plugin PreciousStones v10.0.5 generated an exception while executing task 31
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at ps.org.mcstats.Metrics.postPlugin(Metrics.java:363)
        at ps.org.mcstats.Metrics.access$500(Metrics.java:68)
        at ps.org.mcstats.Metrics$1.run(Metrics.java:255)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

Let me know if you need any further info. This is not causing any in game issues that I can tell, just console spam.

**Comment by marcelo-mason** [comment]
Removed the Metrics code, pick up latest from Jenkins.
