### ISSUE TITLE
Placing a field with "worldguard-repellent: true" throws exception

### ISSUE THREAD

**Issue by Taybosquee** [marcelo-mason/PreciousStones#959]
Placing a field with "worldguard-repellent: true" throws the following exception and causes the field placement to fail. Note; this is not being placed in a WorldGuard region. Fields without this flag still work as intended on place.

PS versions encountered in: 10.0.4 - 10.2.0 (Build #13)
WorldGuard version: Dev build #1653

[19:51:15] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to PreciousStones v10.2.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot19.jar:git-Spigot-cce4667-ff617f7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot19.jar:git-Spigot-cce4667-ff617f7]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot19.jar:git-Spigot-cce4667-ff617f7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot19.jar:git-Spigot-cce4667-ff617f7]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:145) [Spigot19.jar:git-Spigot-cce4667-ff617f7]
	at net.minecraft.server.v1_9_R1.ItemStack.placeItem(ItemStack.java:159) [Spigot19.jar:git-Spigot-cce4667-ff617f7]
	at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:522) [Spigot19.jar:git-Spigot-cce4667-ff617f7]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:888) [Spigot19.jar:git-Spigot-cce4667-ff617f7]
	at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [Spigot19.jar:git-Spigot-cce4667-ff617f7]
	at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [Spigot19.jar:git-Spigot-cce4667-ff617f7]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot19.jar:git-Spigot-cce4667-ff617f7]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_72]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_72]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [Spigot19.jar:git-Spigot-cce4667-ff617f7]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [Spigot19.jar:git-Spigot-cce4667-ff617f7]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot19.jar:git-Spigot-cce4667-ff617f7]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [Spigot19.jar:git-Spigot-cce4667-ff617f7]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [Spigot19.jar:git
Spigot-cce4667-ff617f7]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
**Caused by: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet, but class was expected**
	at net.sacredlabyrinth.Phaed.PreciousStones.managers.WorldGuardManager.isWGRegion(WorldGuardManager.java:46) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.listeners.PSBlockListener.placingFieldChecks(PSBlockListener.java:1126) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.listeners.PSBlockListener.onBlockPlace(PSBlockListener.java:755) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot19.jar:git-Spigot-cce4667-ff617f7]
	... 18 more

**Comment by marcelo-mason** [comment]
See if that did it

**Comment by Taybosquee** [comment]
Works/fixed. Thanks. :)
