### ISSUE TITLE
delete-if-no-permission Not work

### ISSUE THREAD

**Issue by andramil** [marcelo-mason/PreciousStones#979]
Flag delete-if-no-permission doesn't work. It doesn't print any errors in console.
It isnt even hide in /ps info for normal players. I tested it on 1.8.3 and 1.9.2 spigot servers. I have PS 10.1.2 (from spigot website)

I cant also download snapshot version (10.2.3 ?) from http://repo.sacredlabyrinth.net:8080/job/PreciousStones/ - i have time out :(

**Comment by marcelo-mason** [comment]
Url for jenkins is here now http://104.236.246.108:8080/

**Comment by andramil** [comment]
Flag delete-if-no-permission doesn't work still dont work :(

**Comment by marcelo-mason** [comment]
You tried the new build PS 10.3.1?

**Comment by andramil** [comment]
10.3.0

I will try 10.3.1 and tell resoults

2016-05-31 16:39 GMT+02:00 Phaed <notifications@github.com>:

**Comment by andramil** [comment]
It works great ^^

**Comment by andramil** [comment]
After replace 10.1.2 on 10.3.1 i have spam of:

`[17:23:57] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to PreciousStones v10.3.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server2.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server2.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server2.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server2.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [server2.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:724) [server2.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [server2.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [server2.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server2.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server2.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server2.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server2.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server2.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server2.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerInteractEvent.getHand()Lorg/bukkit/inventory/EquipmentSlot;
	at net.sacredlabyrinth.Phaed.PreciousStones.listeners.PSPlayerListener.onPlayerInteract(PSPlayerListener.java:517) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server2.jar:git-Spigot-db6de12-18fbb24]
	... 16 more`

I didnt notice any bugs or lags but it spam a lot in my console.

Tested on 1.8.3 spigot

**Comment by marcelo-mason** [comment]
The newer builds require Spigot 1.9.4

**Comment by andramil** [comment]
on 1.9.2 work good

Is it possible to repair bug with "delete on no permission: for
10.1.2(build from 27-3-2016) for 1.8 serwer?

Anyway thanks a lot for help :)



2016-05-31 17:36 GMT+02:00 Phaed <notifications@github.com>:

**Comment by marcelo-mason** [comment]
Pick up the legacy version from Jenkins.  Just added it, it will build for 1.8

**Comment by andramil** [comment]
Awesome :) it work great!
