### ISSUE TITLE
Last version 

### ISSUE THREAD

**Issue by Marascraft** [marcelo-mason/PreciousStones#987]
Is your plugin's last version compatible with spigot 1.9.4.
Because I'am triying and I get this : 
16:45:26] [Server thread/ERROR]: Could not load 'plugins/PreciousStones-1.8.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: net/sacredlabyrinth/Phaed/PreciousStones/PreciousStones : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[craftbukkit.jar:git-Bukkit-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[craftbukkit.jar:git-Bukkit-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit.jar:git-Bukkit-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugins(CraftServer.java:294) [craftbukkit.jar:git-Bukkit-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.reload(CraftServer.java:723) [craftbukkit.jar:git-Bukkit-0cd0397]
	at org.bukkit.Bukkit.reload(Bukkit.java:548) [craftbukkit.jar:git-Bukkit-0cd0397]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [craftbukkit.jar:git-Bukkit-0cd0397]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) [craftbukkit.jar:git-Bukkit-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:625) [craftbukkit.jar:git-Bukkit-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchServerCommand(CraftServer.java:611) [craftbukkit.jar:git-Bukkit-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.aL(DedicatedServer.java:397) [craftbukkit.jar:git-Bukkit-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:361) [craftbukkit.jar:git-Bukkit-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:639) [craftbukkit.jar:git-Bukkit-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:543) [craftbukkit.jar:git-Bukkit-0cd0397]
	at java.lang.Thread.run(Thread.java:744) [?:1.7.0_55]
Caused by: java.lang.UnsupportedClassVersionError: net/sacredlabyrinth/Phaed/PreciousStones/PreciousStones : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_55]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_55]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_55]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_55]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_55]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_55]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_55]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_55]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_55]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit.jar:git-Bukkit-0cd0397]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit.jar:git-Bukkit-0cd0397]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_55]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_55]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_55]
	at java.lang.Class.forName(Class.java:270) ~[?:1.7.0_55]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[craftbukkit.jar:git-Bukkit-0cd0397]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[craftbukkit.jar:git-Bukkit-0cd0397]
	... 14 more

**Comment by marcelo-mason** [comment]
Yes you downloaded the jar for 1.8, download the regular one which is for 1.9.

**Comment by Marascraft** [comment]
Again ...
Could not load 'plugins/PreciousStones.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: net/sacredlabyrinth/Phaed/PreciousStones/PreciousStones : Unsupported major.minor version 52.0
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[craftbukkit.jar:git-Bukkit-0cd0397]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[craftbukkit.jar:git-Bukkit-0cd0397]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit.jar:git-Bukkit-0cd0397]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugins(CraftServer.java:294) [craftbukkit.jar:git-Bukkit-0cd0397]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.reload(CraftServer.java:723) [craftbukkit.jar:git-Bukkit-0cd0397]
    at org.bukkit.Bukkit.reload(Bukkit.java:548) [craftbukkit.jar:git-Bukkit-0cd0397]
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [craftbukkit.jar:git-Bukkit-0cd0397]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) [craftbukkit.jar:git-Bukkit-0cd0397]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:625) [craftbukkit.jar:git-Bukkit-0cd0397]
    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchServerCommand(CraftServer.java:611) [craftbukkit.jar:git-Bukkit-0cd0397]
    at net.minecraft.server.v1_9_R2.DedicatedServer.aL(DedicatedServer.java:397) [craftbukkit.jar:git-Bukkit-0cd0397]
    at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:361) [craftbukkit.jar:git-Bukkit-0cd0397]
    at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:639) [craftbukkit.jar:git-Bukkit-0cd0397]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:543) [craftbukkit.jar:git-Bukkit-0cd0397]
    at java.lang.Thread.run(Thread.java:744) [?:1.7.0_55]
Caused by: java.lang.UnsupportedClassVersionError: net/sacredlabyrinth/Phaed/PreciousStones/PreciousStones : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_55]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_55]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_55]
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_55]
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_55]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_55]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_55]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_55]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_55]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit.jar:git-Bukkit-0cd0397]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit.jar:git-Bukkit-0cd0397]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_55]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_55]
    at java.lang.Class.forName0(Native Method) ~[?:1.7.0_55]
    at java.lang.Class.forName(Class.java:270) ~[?:1.7.0_55]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[craftbukkit.jar:git-Bukkit-0cd0397]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[craftbukkit.jar:git-Bukkit-0cd0397]
    ... 14 more

I took this one http://104.236.246.108:8080/job/PreciousStones/lastBuild/artifact/target/PreciousStones.jar

**Comment by marcelo-mason** [comment]
You need java 8

**Comment by Marascraft** [comment]
And with PreciousStones 10.0.4 it's working except that I get that : 
[17:03:03] [pool-3-thread-45/WARN]: Exception in thread "pool-3-thread-45" 
[17:03:03] [pool-3-thread-45/WARN]: org.apache.commons.lang.UnhandledException: Plugin PreciousStones v10.0.4 generated an exception while executing task 1413
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
    at ps.org.mcstats.Metrics.postPlugin(Metrics.java:363)
    at ps.org.mcstats.Metrics.access$500(Metrics.java:68)
    at ps.org.mcstats.Metrics$1.run(Metrics.java:255)
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more
So I will stay with this one until I upgrade Java ....
